livekit/agents

- README.md
- examples/detection/detection.py
Also adding flush that I accidentally removed
> Update README with object detection example

- examples/kitt/kitt.py
- examples/kitt/requirements.txt
- livekit-plugins/livekit-plugins-elevenlabs/livekit/plugins/elevenlabs/tts.py
- livekit-plugins/livekit-plugins-elevenlabs/livekit/plugins/elevenlabs/version.py
https://github.com/livekit/agents/issues/134 and https://github.com/livekit/agents/issues/133
> Improvements to ElevenLabs logging + Handling Other Sample Rates

- examples/fal/requirements.txt
> Add missing requirements + version constraints

- .github/workflows/tests.yml
- livekit-plugins/livekit-plugins-nltk/livekit/plugins/nltk/sentence_tokenizer.py
- tests/test_stt.py
- tests/test_tokenizer.py
successful run: https://github.com/livekit/agents/actions/runs/7924193341
> Introduce tests for pull requests

- examples/fal/fal_sd_turbo.py
> remove legacy videoframe api

- livekit-plugins/livekit-plugins-nltk/livekit/plugins/nltk/sentence_tokenizer.py
- livekit-plugins/livekit-plugins-nltk/livekit/plugins/nltk/version.py
Right now iteration ends immediately
> Fix bug in nltk plugin

- livekit-agents/livekit/agents/__init__.py
- livekit-agents/livekit/agents/aio/__init__.py
- livekit-agents/livekit/agents/aio/channel.py
- livekit-agents/livekit/agents/aio/sleep.py
- livekit-agents/livekit/agents/aio/wait_group.py
- livekit-agents/livekit/agents/cli/cli.py
- livekit-agents/livekit/agents/conv_agent.py
- livekit-agents/livekit/agents/http_server.py
- livekit-agents/livekit/agents/job_request.py
- livekit-agents/livekit/agents/llm/__init__.py
- livekit-agents/livekit/agents/llm/function_context.py
- livekit-agents/livekit/agents/llm/llm.py
- livekit-agents/livekit/agents/vad.py
- livekit-agents/livekit/agents/worker.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/__init__.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/llm.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/log.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/models.py
- tests/test_llm.py
> llm abstraction

- livekit-agents/livekit/agents/cli/cli.py
- livekit-agents/livekit/agents/cli/protocol.py
- livekit-agents/livekit/agents/ipc/job_main.py
- livekit-agents/livekit/agents/utils/event_emitter.py
- livekit-agents/livekit/agents/worker.py
reintroduce the `connect` method 😬🤦
`python3 my_worker.py connect --room --participant-identity theo`
> reintroduce connect cmd to the cli

- livekit-agents/livekit/agents/aio/channel.py
- livekit-agents/livekit/agents/aio/sleep.py
- livekit-agents/livekit/agents/cli/cli.py
- livekit-agents/livekit/agents/cli/watcher.py
- livekit-agents/livekit/agents/http_server.py
- livekit-agents/livekit/agents/ipc/job_main.py
- livekit-agents/livekit/agents/ipc/job_process.py
- livekit-agents/livekit/agents/ipc_enc.py
- livekit-agents/livekit/agents/llm/llm.py
- livekit-agents/livekit/agents/tokenize/basic.py
- livekit-agents/livekit/agents/tokenize/token_stream.py
- livekit-agents/livekit/agents/voice_assistant/assistant.py
- livekit-agents/livekit/agents/worker.py
also fix slow reconnection & make livekit-agents work on python 3.9 (still need some work for plugins)
> better reconnection & ignore irrelevant messages

- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/llm.py
fix https://github.com/livekit/agents/issues/280
> fix: optional argument on function calls

- livekit-agents/livekit/agents/tts/stream_adapter.py
- livekit-plugins/livekit-plugins-google/livekit/plugins/google/tts.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/tts.py
also fill the text field on synthesize/chunked requests for the SynthesizedAudio struct
> add concurrent requests to TTS StreamAdapter

- livekit-plugins/livekit-plugins-elevenlabs/livekit/plugins/elevenlabs/__init__.py
- livekit-plugins/livekit-plugins-elevenlabs/livekit/plugins/elevenlabs/models.py
- livekit-plugins/livekit-plugins-elevenlabs/livekit/plugins/elevenlabs/settings.py
- livekit-plugins/livekit-plugins-elevenlabs/livekit/plugins/elevenlabs/tts.py
- livekit-plugins/livekit-plugins-elevenlabs/livekit/plugins/elevenlabs/version.py
- livekit-plugins/livekit-plugins-elevenlabs/setup.py
- tests/test_tts.py
Addresses: https://github.com/livekit/agents/issues/305
> Mp3 Support and Default for 11Labs

- examples/_deployed/kitt/kitt.py
- livekit-agents/livekit/agents/images/__init__.py
- livekit-agents/livekit/agents/images/image.py
- livekit-agents/livekit/agents/llm/__init__.py
- livekit-agents/livekit/agents/llm/chat_context.py
- livekit-agents/livekit/agents/llm/function_context.py
- livekit-agents/livekit/agents/llm/llm.py
- livekit-agents/livekit/agents/version.py
- livekit-agents/setup.py
- livekit-plugins/livekit-plugins-deepgram/setup.py
- livekit-plugins/livekit-plugins-elevenlabs/livekit/plugins/elevenlabs/version.py
- livekit-plugins/livekit-plugins-elevenlabs/setup.py
- livekit-plugins/livekit-plugins-google/livekit/plugins/google/version.py
- livekit-plugins/livekit-plugins-google/setup.py
- livekit-plugins/livekit-plugins-nltk/livekit/plugins/nltk/version.py
- livekit-plugins/livekit-plugins-nltk/setup.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/llm.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/models.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/version.py
- livekit-plugins/livekit-plugins-openai/setup.py
- livekit-plugins/livekit-plugins-silero/livekit/plugins/silero/version.py
- livekit-plugins/livekit-plugins-silero/setup.py
Draft PR for API feedback:
- New `livekit-agents[images]` optional package for image utilities (jpg, png, resizing, etc)
- ChatMessages can now take a list of images
- OpenAI LLM implementation (untested RN but take a look at the strategy and APIs)
> Introduce vision capabilities to LLM

- livekit-agents/livekit/agents/transcription/tts_forwarder.py
- livekit-agents/livekit/agents/utils/__init__.py
- livekit-agents/livekit/agents/utils/log.py
- livekit-agents/livekit/agents/voice_assistant/assistant.py
- livekit-agents/livekit/agents/voice_assistant/plotter.py
- fix swallowed errors 
- cleanup code, try to make stuff more maintainable
- I may split into multiple files once fnc calling is merged
- add more comments as complexity is increasing (more features)
- add preemptive_synthesis bool option
- fix https://github.com/livekit/agents/issues/340
this still need some work on API changes, but this requires some fnc calling stuff so will continue my other PR before
> voice assistant fix ZeroDivisionError & add preemptive_synthesis opt + cleanup

- livekit-agents/livekit/agents/voice_assistant/assistant.py
https://github.com/livekit/agents/pull/357 removed this code
> fix assistant not having the last user msg

- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/llm.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/stt.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/tts.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/utils.py
> Allow custom base_url to be used with OpenAI plugins

- examples/speech-to-text/README.md
- examples/speech-to-text/deepgram_stt.py
The wrong participant object was passed in.
> Fix transcription example

- livekit-agents/livekit/agents/cli/log.py
- livekit-agents/setup.py
- extra is shown by default in both, dev and prod
- removed colorlog and python-json-logger dependencies (current code is based on them)
> add more context to logs

- livekit-agents/livekit/agents/aio/select.py
- livekit-agents/livekit/agents/cli/protocol.py
- livekit-agents/livekit/agents/ipc/protocol.py
- livekit-agents/livekit/agents/job_context.py
- livekit-agents/livekit/agents/job_request.py
- livekit-agents/livekit/agents/llm/function_context.py
- livekit-agents/livekit/agents/llm/llm.py
- livekit-agents/livekit/agents/transcription/tts_forwarder.py
- livekit-agents/livekit/agents/voice_assistant/assistant.py
- livekit-agents/livekit/agents/voice_assistant/plotter.py
- livekit-agents/livekit/agents/worker.py
- livekit-agents/setup.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/llm.py
We only use attrs for the kw_only feature because Python 3.9 doesn't support it (3.10+)
It isn't that important..
> remove attrs dependency

- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/__init__.py
> Adding LLMStream to __init__ for openai-plugin

- livekit-agents/livekit/agents/worker.py
see https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.create_server
> http_server: no specific host by default

- livekit-agents/livekit/agents/ipc/channel.py
- livekit-agents/livekit/agents/ipc/proc_main.py
- livekit-agents/livekit/agents/ipc/proc_pool.py
- livekit-agents/livekit/agents/ipc/supervised_proc.py
- tests/test_ipc.py
- main process hangs if a child was killed?
- also move close timeout to SupervisedProcess
> initialize_timeout & fix pipe deadlock

- livekit-agents/livekit/agents/cli/log.py
- livekit-agents/livekit/agents/cli/watcher.py
- livekit-agents/livekit/agents/log.py
- livekit-agents/livekit/agents/worker.py
so nit, but really helps to separate visually what happened between job excecutions..
> add log levelname

- .github/workflows/publish-package.yml
merges the changes of #450 into the `dev` branch
> Add dev package release workflow

- livekit-agents/livekit/agents/ipc/proc_pool.py
- livekit-agents/livekit/agents/ipc/supervised_proc.py
- tests/test_ipc.py
> fix: ForkServerContext type isn't available on Windows 

- livekit-agents/livekit/agents/worker.py
- tests/test_ipc.py
basically https://github.com/livekit/agents/pull/459
> fix wrong load reports & task leaks

- examples/_deployed/README.md
- examples/_deployed/kitt/Dockerfile
- examples/_deployed/kitt/kitt.py
> Revert "Remove _deployed dir"

- examples/voice-assistant/minimal_assistant.py
- examples/voice-assistant/requirements.txt
- livekit-agents/livekit/agents/voice_assistant/agent_output.py
- livekit-agents/livekit/agents/voice_assistant/voice_assistant.py
> voiceassistant: cleanup validation behaviour 

- livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/stt.py
> deepgram: segment audio frames into 200ms intervals before sending to the websocket

- .changeset/many-clocks-punch.md
- .changeset/perfect-doors-play.md
- livekit-agents/livekit/agents/cli/log.py
- livekit-agents/livekit/agents/plugin.py
- livekit-agents/livekit/agents/voice_assistant/agent_output.py
- livekit-agents/livekit/agents/voice_assistant/agent_playout.py
- livekit-agents/livekit/agents/voice_assistant/voice_assistant.py
- livekit-plugins/livekit-plugins-azure/livekit/plugins/azure/__init__.py
- livekit-plugins/livekit-plugins-cartesia/livekit/plugins/cartesia/__init__.py
- livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/__init__.py
- livekit-plugins/livekit-plugins-elevenlabs/livekit/plugins/elevenlabs/__init__.py
- livekit-plugins/livekit-plugins-google/livekit/plugins/google/__init__.py
- livekit-plugins/livekit-plugins-minimal/livekit/plugins/minimal/__init__.py
- livekit-plugins/livekit-plugins-minimal/livekit/plugins/minimal/log.py
- livekit-plugins/livekit-plugins-nltk/livekit/plugins/nltk/__init__.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/__init__.py
- livekit-plugins/livekit-plugins-rag/livekit/plugins/rag/__init__.py
- livekit-plugins/livekit-plugins-silero/livekit/plugins/silero/__init__.py
- configure plugins logger
- CancellableAudioSource -> AgentPlayout
- Added speech_id to recognize synthesized speech in logs
- more logs on the VoiceAssistant
- added Plugin registration events
> configure plugins loggers & more debug logs on the voiceassistant

- .changeset/warm-ducks-suffer.md
- examples/voice-assistant/function_calling.py
- livekit-agents/livekit/agents/voice_assistant/agent_output.py
- livekit-agents/livekit/agents/voice_assistant/agent_playout.py
- livekit-agents/livekit/agents/voice_assistant/voice_assistant.py
- fix join_fut being undefined when user_speech_committed was first called
- fix speech being removed too soon from the queue (preventing some interruption scenarios)
- fix some very late transcripts never being validated
> voiceassistant: tweaks & fix speech being removed too soon from the queue

- .changeset/weak-crews-whisper.md
- livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/stt.py
> conversationalai: Optimized for use cases in which a human is talking to an automated bot, such as IVR, a voice assistant, or an automated kiosk.
https://developers.deepgram.com/docs/model#nova-2
> deepgram: update default model to nova-2-conversationalai

- .changeset/late-rockets-double.md
- livekit-agents/livekit/agents/voice_assistant/agent_playout.py
- livekit-agents/livekit/agents/voice_assistant/voice_assistant.py
cancelled could still be False in some cases
> voiceassistant: fix complete transcription still sent after interruption

- .changeset/thin-apricots-end.md
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/llm.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/models.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/stt.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/tts.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/utils.py
- Primarily for consistency with other openai interfaces
- also fix tests
http_session has been replaced by the openai client
> openai: use openai client for stt

- .changeset/yellow-bags-cry.md
- livekit-agents/livekit/agents/tts/stream_adapter.py
- livekit-agents/livekit/agents/tts/tts.py
- livekit-agents/livekit/agents/voice_assistant/agent_output.py
- livekit-agents/livekit/agents/voice_assistant/voice_assistant.py
the synthesis of speech was still happening even after an interruption. 
this PR also adds more logs for ttft
> voiceassistant: fix synthesis continuing after interruption

- .changeset/small-badgers-drop.md
- examples/voice-assistant/minimal_assistant.py
- livekit-agents/livekit/agents/transcription/stt_forwarder.py
- livekit-agents/livekit/agents/transcription/tts_forwarder.py
- livekit-agents/livekit/agents/voice_assistant/agent_output.py
- livekit-agents/livekit/agents/voice_assistant/agent_playout.py
- livekit-agents/livekit/agents/voice_assistant/human_input.py
- livekit-agents/livekit/agents/voice_assistant/voice_assistant.py
This is useful when the speech was interrupted. This makes sure the LLM has the same "context" as what the user heard
> voiceassistant: only commit the spoken words in the chat context

- .changeset/chilly-days-rhyme.md
- livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/stt.py
Example:
```
assistant = VoiceAssistant(
vad=silero.VAD.load(),
stt=deepgram.STT(keywords=[("livekit", 10.0), ("cartesia", 10.0)]),
llm=openai.LLM(),
tts=cartesia.TTS(),
chat_ctx=initial_ctx,
)
```
> deepgram: add support for keywords boost/penalty

- .changeset/itchy-ligers-exist.md
- livekit-plugins/livekit-plugins-nltk/livekit/plugins/nltk/__init__.py
- livekit-plugins/livekit-plugins-nltk/setup.py
NLTK made a breaking API change in a patch version :)
Reference-To: https://github.com/nltk/nltk/issues/3293
> nltk: fix broken punkt download

- livekit-agents/livekit/agents/voice_assistant/agent_playout.py
the reason is that it doesn't feel human at all
> voiceassistant: remove fade effect when interrupting

- livekit-agents/livekit/agents/__init__.py
- livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/stt.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/models.py
also a few driveby:
* export WorkerPermissions
* add gpt-4o-mini to models
> Fix deepgram English check

- .changeset/long-gorillas-bake.md
- livekit-plugins/livekit-plugins-rag/livekit/plugins/rag/__init__.py
I just added:
def download_files(self) -> None:
pass
and It worked!
> Modified RAG plugin

- .changeset/funny-squids-help.md
- .changeset/itchy-ligers-exist.md
- livekit-plugins/livekit-plugins-nltk/livekit/plugins/nltk/__init__.py
- livekit-plugins/livekit-plugins-nltk/setup.py
> Revert "nltk: fix broken punkt download"

- .changeset/six-foxes-provide.md
- livekit-agents/livekit/agents/ipc/proto.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/llm.py
Fixes #612
chose to add it to `chat()` but might make sense to add it to `LLM()`.
> openai: allow sending user IDs

- .changeset/fluffy-hornets-vanish.md
- livekit-agents/livekit/agents/voice_assistant/speech_handle.py
- livekit-agents/livekit/agents/voice_assistant/voice_assistant.py
- happens rarely tho (maybe more when your speech is tiny)
> voiceassistant: fix llm not having the full chat context on bad interruption timing

- .changeset/brown-games-greet.md
- .changeset/fluffy-hornets-vanish.md
- .changeset/shaggy-onions-kick.md
- examples/simple-color/requirements.txt
- examples/speech-to-text/requirements.txt
- examples/text-to-speech/requirements.txt
- examples/voice-assistant/requirements.txt
- livekit-agents/CHANGELOG.md
- livekit-agents/livekit/agents/version.py
- livekit-agents/package.json
- livekit-plugins/livekit-plugins-browser/CHANGELOG.md
- livekit-plugins/livekit-plugins-browser/livekit/plugins/browser/version.py
- livekit-plugins/livekit-plugins-browser/package.json
- livekit-plugins/livekit-plugins-nltk/CHANGELOG.md
- livekit-plugins/livekit-plugins-nltk/livekit/plugins/nltk/version.py
- livekit-plugins/livekit-plugins-nltk/package.json
> Revert "Version Packages"

- .changeset/brown-plants-search.md
- livekit-agents/livekit/agents/voice_assistant/voice_assistant.py
> fix uninitialized SpeechHandle error on interruption 

- .changeset/cuddly-steaks-cover.md
- livekit-agents/livekit/agents/ipc/proc_main.py
fix a breaking change from livekit-rtc>=0.13
> fix: disconnect event may now have some arguments 

- .changeset/famous-panthers-cough.md
- livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/stt.py
see https://github.com/orgs/deepgram/discussions/902
> deepgram: switch the default model to phonecall

- .changeset/stale-mangos-peel.md
- examples/text-to-speech/elevenlabs_tts.py
- examples/text-to-speech/openai_tts.py
- examples/text-to-speech/sync_tts_transcription.py
- examples/voice-assistant/function_calling.py
- examples/voice-assistant/minimal_assistant.py
- examples/voice-assistant/simple-rag/assistant.py
- livekit-agents/livekit/agents/voice_assistant/voice_assistant.py
- livekit-agents/setup.py
awaited in voice_assistant, examples updated for tts.
> update livekit to 0.14.0 and await tracksubscribed

- .changeset/shy-toys-fix.md
- livekit-agents/livekit/agents/ipc/proc_main.py
attempt to fix https://github.com/livekit/agents/issues/690
> fix non pickleable log

- .changeset/early-guests-join.md
- examples/text-to-speech/elevenlabs_tts.py
- examples/text-to-speech/openai_tts.py
- examples/text-to-speech/sync_tts_transcription.py
- livekit-plugins/livekit-plugins-google/livekit/plugins/google/tts.py
> google-tts: ignore wav header

- .changeset/afraid-hairs-tie.md
- livekit-agents/livekit/agents/ipc/proc_main.py
- livekit-agents/livekit/agents/job.py
also added docstrings to other methods
> Ensure room.name is available before connection

- .changeset/hungry-wasps-tell.md
- examples/simple-color/agent.py
- examples/voice-assistant/minimal_assistant.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/llm.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/models.py
This MR does the following changes:
1.  Added support for DeepSeek LLM:
2. Updated examples: Modified minimal_assistant.py to use DeepSeek LLM
3. Refactored simple-color/agent.py to generate random colors instead of using a fixed color
4. Minor improvements:
1) Added environment variable loading in simple-color/agent.py
2) Updated WorkerOptions in simple-color/agent.py to include an agent name
> Add deepseek LLMs at OpenAI plugin

- .changeset/tall-falcons-work.md
- livekit-agents/livekit/agents/utils/aio/__init__.py
- livekit-agents/setup.py
> bump required livekit version to 0.15.2

- .changeset/late-panthers-chew.md
- livekit-agents/livekit/agents/transcription/tts_forwarder.py
- livekit-agents/livekit/agents/voice_assistant/agent_output.py
don't raise exceptions, just create an empty segment, this makes it easier to reason about it
> tts_forwarder: don't raise inside mark_{audio,text}_segment_end when nothing was pushed

- .changeset/swift-dodos-attack.md
- README.md
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/llm.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/models.py
Adds integration with http://cerebras.ai/ to the OpenAI plugin.
> Add Cerebras to OpenAI Plugin

- examples/speech-to-text/README.md
Updated to refer to https://github.com/livekit/web/pull/315
> Update STT sample README

- .changeset/quiet-eagles-add.md
- livekit-agents/livekit/agents/ipc/proc_pool.py
> limit concurrent process init to 1 

- examples/voice-assistant/custom_pronunciation.py
- livekit-agents/livekit/agents/cli/cli.py
- livekit-agents/livekit/agents/cli/log.py
- livekit-agents/livekit/agents/cli/proto.py
- livekit-agents/livekit/agents/ipc/proc_lazy_main.py
- livekit-agents/livekit/agents/log.py
- livekit-agents/livekit/agents/worker.py
in dev mode:
- don't prewarm processes 
- http server defaults to a random available port
- default log level to debug
- disable load threshold for capacity (always accept)
> better dev defaults

- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/beta/assistant_llm.py
The were definitely not written by me
> Remove useless logs

- .changeset/shiny-eyes-itch.md
- README.md
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/llm.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/models.py
Adds integration with [Telnyx Inference](https://developers.telnyx.com/docs/inference/getting-started) to the OpenAI plugin, at which point we can also update our [LiveKit Voice Assistant Integration guide](https://developers.telnyx.com/docs/inference/livekit)
> Add Telnyx integration for LLM

- .changeset/four-ways-end.md
- livekit-agents/livekit/agents/pipeline/pipeline_agent.py
- livekit-agents/livekit/agents/stt/stream_adapter.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/stt.py
> fix: handle when STT does not return any speech

- .changeset/yellow-eggs-shout.md
- livekit-agents/livekit/agents/pipeline/pipeline_agent.py
> Handle llm stream returning false

- .changeset/brown-schools-reply.md
- livekit-agents/livekit/agents/pipeline/pipeline_agent.py
- livekit-agents/livekit/agents/pipeline/speech_handle.py
Agent state would update to listening when the user started speaking, even if the agent was still speaking.
This also fixes some bugs where uninterruptable speech would actually be interrupted.
> Fix agent state

- .changeset/good-horses-explain.md
- livekit-agents/livekit/agents/cli/log.py
- livekit-agents/livekit/agents/pipeline/agent_output.py
- livekit-agents/livekit/agents/pipeline/pipeline_agent.py
- livekit-agents/livekit/agents/transcription/tts_forwarder.py
fix https://github.com/livekit/agents/issues/797
> voice-pipeline: fix tts_forwarder not always being closed

- .changeset/selfish-penguins-shop.md
- livekit-agents/livekit/agents/worker.py
> improve logs

- .changeset/six-suits-shake.md
- .changeset/strong-lobsters-push.md
- livekit-agents/livekit/agents/llm/chat_context.py
- livekit-agents/livekit/agents/pipeline/pipeline_agent.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/llm.py
It seems the other providers also exclude content - however I'm not using them so wasn't able to test.
> OpenAI - Include content in function call results

- .changeset/five-lobsters-mate.md
- livekit-plugins/livekit-plugins-google/livekit/plugins/google/tts.py
- Added arguments to Google TTS class to accept and set Pitch and Audio Effect Profiles.
> Additional options enabled on Google TTS

- .changeset/sharp-dancers-develop.md
- livekit-agents/livekit/agents/pipeline/pipeline_agent.py
I've gotten tripped up by this a bunch.
> Log exception on tool error

- .changeset/twenty-poems-whisper.md
- livekit-agents/livekit/agents/pipeline/pipeline_agent.py
> voicepipeline: support recursive/chained function calls

- livekit-agents/livekit/agents/worker.py
> Fixed bad import in the last commit

- .changeset/eleven-items-love.md
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/models.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/stt.py
Fixes https://github.com/livekit/agents/issues/981
Please review @davidzhao @theomonnom
> whisper: add groq support

- livekit-agents/livekit/agents/utils/hw/cpu.py
Fix https://github.com/livekit/agents/issues/1000
> fix: fallback when cpu.max not found

- examples/voice-pipeline-agent/pipeline_metrics.py
- livekit-agents/livekit/agents/stt/stream_adapter.py
- livekit-agents/livekit/agents/tts/stream_adapter.py
- livekit-agents/livekit/agents/tts/tts.py
- livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/stt.py
- tests/test_tts.py
- also fix metrics being emitted twice when using the StreamAdapter
> pipelineagent: add metrics example

- .changeset/good-monkeys-march.md
- livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/stt.py
> deepgram: send finalize each time we stop sending audio

- .changeset/neat-islands-drum.md
- livekit-agents/livekit/agents/cli/log.py
- livekit-agents/livekit/agents/llm/llm.py
- livekit-agents/livekit/agents/stt/stt.py
- livekit-agents/livekit/agents/tts/tts.py
- livekit-agents/livekit/agents/vad.py
- livekit-plugins/livekit-plugins-anthropic/livekit/plugins/anthropic/llm.py
- also fix some errors propagation
> fix: invalid request on anthropic

- .changeset/unlucky-bananas-run.md
- livekit-agents/livekit/agents/tts/tts.py
> fix: IndexError on tts metrics

- .changeset/new-games-change.md
- livekit-plugins/livekit-plugins-google/livekit/plugins/google/stt.py
fixes : https://github.com/livekit/agents/issues/852
> google stt fix abort

- .changeset/blue-files-melt.md
- examples/voice-pipeline-agent/minimal_assistant.py
- livekit-agents/livekit/agents/pipeline/pipeline_agent.py
- livekit-agents/livekit/agents/worker.py
> Fix interrupt_min_words handling

- .changeset/poor-toes-call.md
- livekit-plugins/livekit-plugins-azure/livekit/plugins/azure/stt.py
- livekit-plugins/livekit-plugins-azure/livekit/plugins/azure/tts.py
Add support for azure speech containers: https://learn.microsoft.com/en-us/azure/ai-services/speech-service/speech-container-stt?tabs=container&pivots=programming-language-python#use-the-container
> fix: support azure speech running in containers

- .changeset/nice-bags-bake.md
- .github/workflows/tests.yml
- livekit-agents/livekit/agents/stt/stt.py
- livekit-plugins/livekit-plugins-assemblyai/livekit/plugins/assemblyai/stt.py
- livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/stt.py
- tests/test_stt.py
Leveraging common utils including streaming resampler
> Updated assembly.ai integration

- .changeset/fair-chefs-complain.md
- livekit-plugins/livekit-plugins-deepgram/setup.py
> add changeset for PeriodicCollector

- .changeset/mighty-falcons-cheer.md
- livekit-agents/setup.py
> relax Pillow version for Python 3.13 support

- .changeset/tender-emus-tickle.md
- examples/voice-pipeline-agent/function_calling_weather.py
- livekit-agents/livekit/agents/pipeline/pipeline_agent.py
- livekit-agents/livekit/agents/pipeline/speech_handle.py
Replace https://github.com/livekit/agents/pull/1112 for https://github.com/livekit/agents/issues/1054
> feat: nested speech handles

- .changeset/olive-shirts-clap.md
- livekit-plugins/livekit-plugins-azure/livekit/plugins/azure/stt.py
- livekit-plugins/livekit-plugins-azure/livekit/plugins/azure/tts.py
Adds Microsoft Entra authentication for Azure STT and TTS.
> azure: support entra auth token

- .changeset/cool-sheep-shave.md
- livekit-plugins/livekit-plugins-playht/livekit/plugins/playht/models.py
- livekit-plugins/livekit-plugins-playht/livekit/plugins/playht/tts.py
Ensure the sample_rate is included in the JSON data for text-to-speech requests, aligning with other audio options.
> fix(playht): add sample_rate parameter to JSON payload

- livekit-agents/livekit/agents/llm/chat_context.py
- livekit-plugins/livekit-plugins-anthropic/livekit/plugins/anthropic/llm.py
Very basic usage doc. I also updated the error message from the anthropic plugin to be easier to understand (the old one wasn't clear it came from LiveKit plugins rather than from Anthropic itself)
> Add docs to ChatImage

- .changeset/fast-houses-yell.md
- livekit-plugins/livekit-plugins-anthropic/livekit/plugins/anthropic/llm.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/utils.py
This PR imeplements structured output return from function calls.
> feat: return structured output from func calls

- examples/voice-pipeline-agent/minimal_assistant.py
- examples/voice-pipeline-agent/requirements.txt
not quite ready yet due to pytorch dep. will re-enable once that's resolved.
> remove turn_detector from minimal_assistant

- .changeset/famous-points-tickle.md
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model.py
For https://github.com/livekit/agents/issues/1056
> fix: cancel active response for tool call in multimodal agent

- .changeset/empty-sheep-pump.md
- .github/workflows/tests.yml
- livekit-agents/livekit/agents/stt/stt.py
- livekit-agents/livekit/agents/utils/codecs/__init__.py
- livekit-agents/livekit/agents/utils/codecs/decoder.py
- livekit-agents/setup.py
- livekit-plugins/install_local.sh
- livekit-plugins/livekit-plugins-deepgram/setup.py
- tests/.gitattributes
- tests/change-sophie.opus
- tests/test_decoder.py
- tests/test_stt.py
also moved it to an executor, to avoid decoding while blocking async runloop
> streaming audio decoder, enables receiving compressed audio from TTS services

- livekit-agents/livekit/agents/metrics/base.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model.py
https://github.com/livekit/agents/issues/1247
> Added cached_token_details to multimodalllmmetrics

- .changeset/grumpy-dancers-develop.md
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model.py
For https://github.com/livekit/agents/issues/1244
> fix: filter out empty message for set chat ctx in realtime model

- examples/hive-moderation-agent/README.md
- examples/hive-moderation-agent/agent.py
- examples/hive-moderation-agent/hive_data_classes.py
- examples/hive-moderation-agent/requirements.txt
I took @dsa's Hive moderation agent from his personal repo and updated it to the latest API and standards for our examples.  I tested it using a key from Hive and our agent playground.
> examples: updated, tested, and added @dsa's Hive moderation agent

- .changeset/dirty-mails-reflect.md
- .changeset/four-rockets-accept.md
- livekit-agents/livekit/agents/pipeline/pipeline_agent.py
- livekit-plugins/livekit-plugins-turn-detector/setup.py
also make max_endpoint_delay configurable
> Add jinja2 dependency to turn detector

- .changeset/six-wasps-pay.md
- livekit-agents/livekit/agents/ipc/supervised_proc.py
> fix: do not log process warning when process not found

- .changeset/eight-lemons-hear.md
- livekit-agents/livekit/agents/cli/proto.py
- livekit-agents/livekit/agents/ipc/proto.py
- livekit-agents/livekit/agents/job.py
- livekit-agents/livekit/agents/worker.py
- tests/test_ipc.py
implements https://github.com/livekit/agents/issues/1304
> expose worker_id in jobcontext

- .changeset/slow-walls-bake.md
- livekit-agents/livekit/agents/pipeline/pipeline_agent.py
- livekit-agents/livekit/agents/pipeline/speech_handle.py
Add `interrupt` method for pipeline agent. 
Related to https://github.com/livekit/agents/issues/1179
> fix: add manual interrupt for pipeline agent

- livekit-plugins/livekit-plugins-google/livekit/plugins/google/beta/realtime/realtime_api.py
Fix a minor typo in realtime Gemini live docstring…
> Fix env var typo

- .changeset/purple-turtles-arrive.md
- livekit-plugins/livekit-plugins-elevenlabs/livekit/plugins/elevenlabs/tts.py
> Add language param to ElevenLabs TTS update_options

- .changeset/gorgeous-trees-work.md
> added a changeset to publish Fal

- livekit-agents/livekit/agents/pipeline/pipeline_agent.py
- livekit-agents/livekit/agents/pipeline/speech_handle.py
Add nested_speech_done_fut only if nested speech loop starts
> fix nested speech done future

- .changeset/sour-gorillas-jam.md
- livekit-agents/livekit/agents/tts/tts.py
- livekit-plugins/livekit-plugins-cartesia/livekit/plugins/cartesia/tts.py
- livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/tts.py
- livekit-plugins/livekit-plugins-elevenlabs/livekit/plugins/elevenlabs/tts.py
- livekit-plugins/livekit-plugins-playai/livekit/plugins/playai/tts.py
for streaming TTS that were sentence based, it was counting the time to generate the first sentence in the TTFB metrics.
> improved TTFB metrics for streaming TTS

- .changeset/five-rats-impress.md
- livekit-agents/livekit/agents/pipeline/agent_output.py
> fix agent transcription could not be disabled

- .changeset/lemon-glasses-yell.md
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/llm.py
fixes: https://github.com/livekit/agents/issues/1470
and minor improvements
> fix: [openai] only send params when set

- .changeset/slow-toys-scream.md
- livekit-agents/livekit/agents/ipc/job_proc_lazy_main.py
- livekit-agents/livekit/agents/job.py
I made this backward compatible, which I think is a nicer interface anyway since people don't always care about the shutdown reason.
> Allow shutdown to take reason

- .changeset/popular-weeks-drive.md
- examples/voice-pipeline-agent/function_calling_weather.py
- livekit-agents/livekit/agents/tts/stream_adapter.py
- livekit-agents/livekit/agents/utils/codecs/decoder.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/tts.py
this eliminates the audio glitches that sometimes happens with OAI TTS when using PCM.
it also fixes leaked tasks with StreamAdapter
> openai tts: switch to using Opus encoding

- .changeset/breezy-adults-carry.md
- livekit-plugins/livekit-plugins-google/livekit/plugins/google/stt.py
> fix(google): require min confidence score due to aggressive generation

- .changeset/spotty-donkeys-give.md
- livekit-agents/livekit/agents/cli/cli.py
> Revert "fix(cli): update main_file path to use current directory"

- .changeset/cuddly-impalas-share.md
- livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/stt.py
closes https://github.com/livekit/agents/issues/1533
> fix(deepgram): fix STT keyterm parameter

- .changeset/dry-items-fly.md
#1508 was merged without changeset.. adding them here
> adding missing changeset from #1508

- .changeset/nasty-ravens-think.md
- livekit-plugins/livekit-plugins-google/livekit/plugins/google/beta/realtime/realtime_api.py
fixes: https://github.com/livekit/agents/issues/1561
> fix: update function call cancellation ids

- .changeset/nervous-birds-relax.md
- examples/multimodal-agent/openai_agent.py
- livekit-agents/livekit/agents/multimodal/multimodal_agent.py
- livekit-plugins/livekit-plugins-google/livekit/plugins/google/beta/realtime/realtime_api.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model.py
> fix multimodal agent interrupts itself during function call

- examples/roomio_worker.py
- livekit-agents/livekit/agents/voice/chat_cli.py
- livekit-agents/livekit/agents/voice/room_io.py
- livekit-agents/livekit/agents/voice/voice_agent.py
- livekit-agents/setup.py
requires `livekit-plugins-noise-cancellation` package.
> integrate krisp to 1.0

- .changeset/vast-wolves-share.md
https://github.com/livekit/agents/pull/1626/files
> add changeset for cartesia 

- examples/parallel_fnc_agent.py
- livekit-agents/livekit/agents/llm/utils.py
- livekit-agents/livekit/agents/voice/generation.py
- livekit-agents/livekit/agents/voice/task_activity.py
* fix the fnc call output
* fix fnc call speech for realtime model
* TBD: fix the parallel function calls in pipeline agent
> fix fnc calls and add parallel fnc calls test

- .changeset/green-jobs-own.md
- livekit-plugins/livekit-plugins-azure/livekit/plugins/azure/tts.py
We make the callbacks from #1486 updatable options.
> Add Azure TTS callbacks as updatable options

- .changeset/modern-pandas-hunt.md
- livekit-plugins/livekit-plugins-google/livekit/plugins/google/beta/realtime/api_proto.py
- livekit-plugins/livekit-plugins-google/livekit/plugins/google/beta/realtime/realtime_api.py
fixes: https://github.com/livekit/agents/issues/1653
> allow configurable api version in gemini realtime

- .changeset/two-singers-greet.md
- livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/stt.py
fixes :https://github.com/livekit/agents/issues/1666
> support numerals for deepgram stt

- .changeset/dirty-snakes-doubt.md
- .changeset/seven-impalas-glow.md
- livekit-agents/livekit/agents/types.py
- livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/stt.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/__init__.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/models.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/stt.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/tts.py
- livekit-plugins/livekit-plugins-openai/setup.py
also introducing streaming STT support
> Support for OpenAI's new TTS and STT models

- .changeset/lucky-symbols-think.md
- livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/stt.py
In order to prevent data to be used for model training
> Allow opting out from deepgram model improvement plan

- .changeset/cold-plants-allow.md
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/stt.py
exposing vad options when in realtime mode: https://platform.openai.com/docs/guides/realtime-vad
> expose turn_detection options with openai STT

- livekit-agents/livekit/agents/voice/chat_cli.py
https://github.com/livekit/agents/commit/6bb140dc619219f4674917a81c464c5d79523d1b Missed refactoring the CLI audio output initialization.
> Fix broken console mode

- .github/next-release/changeset-aad3138e.md
- examples/voice_agents/dynamic_tool_creation.py
- livekit-agents/livekit/agents/llm/tool_context.py
ideally pydantic adds support for "`choices`" in their `Field` dataclass for better devex
otherwise any BaseModel/common python types work
> support dynamic tool creation

- livekit-agents/livekit/agents/utils/codecs/decoder.py
This should address #1693 by calling send_nowait in the main thread.
> use call_soon_threadsafe

- .github/workflows/changesets.yml
- .github/workflows/ci.yml
- .github/workflows/tests.yml
- README.md
> Update branch references

- .github/next-release/changeset-d4c5540e.md
- livekit-agents/livekit/agents/utils/codecs/decoder.py
- not sure if this was the cause of some mem leak reported in the last 0.x version
> cleanup AudioStreamDecoder resources

- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model.py
Expose the `temperature` parameter for OpenAI Realtime model.
> Support `temperature` configuration for OpenAI Realtime model

- .github/workflows/publish-docs.yml
- livekit-plugins/install_local.sh
This is an easy update that doesn't require migrating `0.x` to `uv`
> fix(ci): restore legacy docs deployment

- livekit-plugins/install_local.sh
Whoops, missed `livekit-plugins-groq` in the local install list.
> fix(ci): add groq to docs build list

- .github/next-release/changeset-6664dcf4.md
- livekit-agents/livekit/agents/voice/room_io/room_io.py
> ability to disable transcription sync

- .github/next-release/changeset-9108deb1.md
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model.py
- uv.lock
this will fail the realtime session due to pydantic serializing to null temperature
> fix(openai): do not pass in None for temperature

- livekit-agents/livekit/agents/llm/realtime.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model.py
We want to support clearing input audio buffer using OpenAI Realtime API.
> Implement  `clear_audio` method for OpenAI Realtime model

- examples/full_examples/restaurant_agent/restaurant_agent.py
make it more stable for users to go back and forth with the agent, like adding a new item to the order during checkout.
> add tool descriptions for the restaurant example

- .github/next-release/changeset-b5676ad3.md
- livekit-agents/livekit/agents/llm/chat_context.py
> add: ChatMessage.text_content() to retrieve text from message

- .github/next-release/changeset-82324a24.md
- livekit-plugins/livekit-plugins-anthropic/livekit/plugins/anthropic/llm.py
- livekit-plugins/livekit-plugins-anthropic/livekit/plugins/anthropic/utils.py
- livekit-plugins/livekit-plugins-aws/livekit/plugins/aws/llm.py
- livekit-plugins/livekit-plugins-aws/livekit/plugins/aws/utils.py
- livekit-plugins/livekit-plugins-google/livekit/plugins/google/llm.py
- livekit-plugins/livekit-plugins-google/livekit/plugins/google/utils.py
fixes: https://github.com/livekit/agents/issues/1828 and https://github.com/livekit/agents/issues/1828
> fix tool choice and empty content error in LLM plugins

- .github/next-release/changeset-e0133da1.md
- examples/voice_agents/multi_agent.py
- livekit-agents/livekit/agents/job.py
- livekit-agents/pyproject.toml
- livekit-plugins/livekit-plugins-anthropic/pyproject.toml
- livekit-plugins/livekit-plugins-assemblyai/pyproject.toml
- livekit-plugins/livekit-plugins-aws/pyproject.toml
- livekit-plugins/livekit-plugins-azure/pyproject.toml
- livekit-plugins/livekit-plugins-cartesia/pyproject.toml
- livekit-plugins/livekit-plugins-clova/pyproject.toml
- livekit-plugins/livekit-plugins-deepgram/pyproject.toml
- livekit-plugins/livekit-plugins-elevenlabs/pyproject.toml
- livekit-plugins/livekit-plugins-groq/pyproject.toml
- livekit-plugins/livekit-plugins-llama-index/pyproject.toml
- livekit-plugins/livekit-plugins-minimal/pyproject.toml
- livekit-plugins/livekit-plugins-neuphonic/pyproject.toml
- livekit-plugins/livekit-plugins-nltk/pyproject.toml
- livekit-plugins/livekit-plugins-openai/pyproject.toml
- livekit-plugins/livekit-plugins-playai/pyproject.toml
- livekit-plugins/livekit-plugins-rag/pyproject.toml
- livekit-plugins/livekit-plugins-rime/pyproject.toml
- livekit-plugins/livekit-plugins-silero/pyproject.toml
- livekit-plugins/livekit-plugins-speechmatics/pyproject.toml
- livekit-plugins/livekit-plugins-turn-detector/pyproject.toml
- uv.lock
HTTP session lifecycle is now automatically managed if one uses `ctx.api`
> use shared http session

- .github/next-release/changeset-b2c37f38.md
- examples/voice_agents/basic_agent.py
- livekit-plugins/livekit-plugins-elevenlabs/livekit/plugins/elevenlabs/models.py
- livekit-plugins/livekit-plugins-elevenlabs/livekit/plugins/elevenlabs/tts.py
reduces TTFB by 11labs by about 110ms
also making encoding customizable again
> use 22.05khz by default for 11labs

- .github/next-release/changeset-56dd097d.md
- livekit-plugins/livekit-plugins-azure/livekit/plugins/azure/stt.py
fixes: https://github.com/livekit/agents/issues/1858
> fix azure language

- livekit-plugins/livekit-plugins-google/livekit/plugins/google/tts.py
reference
- https://cloud.google.com/text-to-speech/docs/reference/rest#service-endpoint
- https://github.com/GoogleCloudPlatform/generative-ai/blob/main/audio/speech/getting-started/get_started_with_chirp_3_hd_voices.ipynb
> google tts: configure api_endpoint based on location

- .changeset/swift-avocados-kiss.md
- livekit-plugins/livekit-plugins-google/livekit/plugins/google/tts.py
reference
- https://cloud.google.com/text-to-speech/docs/reference/rest#service-endpoint
- https://github.com/GoogleCloudPlatform/generative-ai/blob/main/audio/speech/getting-started/get_started_with_chirp_3_hd_voices.ipynb
> [0.x] google tts: configure api_endpoint based on location

- .github/next-release/changeset-aecf48d3.md
- livekit-agents/livekit/agents/llm/utils.py
- livekit-plugins/livekit-plugins-google/livekit/plugins/google/llm.py
- livekit-plugins/livekit-plugins-google/livekit/plugins/google/utils.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/llm.py
> gemini: support structured output

- .github/next-release/changeset-03076077.md
- livekit-agents/livekit/agents/voice/generation.py
fix update_instructions when the idx of instructions is 0
> fix update_instructions

- livekit-agents/livekit/agents/__init__.py
- livekit-agents/livekit/agents/voice/generation.py
Raising ToolError will give a message to the LLM. Otherwise the agent will say smtgh went wrong to the user
> fix exceptions inside function tools 

- livekit-agents/livekit/agents/metrics/base.py
- livekit-agents/livekit/agents/stt/stt.py
This was confusing a bunch of ppl, I think this is a better default
> set STTMetrics duration to 0.0 when using streaming

- examples/voice_agents/error_callback.py
- examples/voice_agents/realtime_turn_detector.py
- examples/voice_agents/requirements.txt
- examples/voice_agents/silent_function_call.py
- examples/voice_agents/toggle_io.py
- examples/voice_agents/web_search.py
- livekit-agents/livekit/agents/voice/agent_activity.py
> add websearch example & cleanup

- livekit-agents/livekit/agents/llm/llm.py
- livekit-agents/livekit/agents/stt/stt.py
- livekit-agents/livekit/agents/tts/tts.py
> remove error fields

- livekit-agents/livekit/agents/voice/agent_activity.py
> fix unserializable json on debug events

- livekit-agents/livekit/agents/stt/fallback_adapter.py
to fix https://github.com/livekit/agents/issues/1932
> fix: make STT fallback more robust

- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model.py
- tests/test_config.py
> add with_azure in openai realtime

- livekit-agents/livekit/agents/voice/__init__.py
- livekit-agents/livekit/agents/voice/events.py
Adds missing FunctionToolsExecutedEvent export in voice agents module
> fix: add missing FunctionToolsExecutedEvent export

- .github/next-release/changeset-4ffe605b.md
- livekit-plugins/livekit-plugins-google/livekit/plugins/google/tts.py
fixes: https://github.com/livekit/agents/issues/1912
> simplify google tts voice params

- .github/next-release/changeset-a1f0d782.md
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model.py
semantic vad is gives error on azure openai
> fix realtime default turn detection and transcription for azure openai

- livekit-plugins/livekit-plugins-speechify/livekit/plugins/speechify/tts.py
- Changed default voice
- Add x-caller header
> Speechify TTS Plugin Improvements

- examples/voice_agents/raw_function_description.py
- livekit-agents/livekit/agents/llm/__init__.py
- livekit-agents/livekit/agents/llm/realtime.py
- livekit-agents/livekit/agents/llm/tool_context.py
- livekit-agents/livekit/agents/voice/generation.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/tts.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/utils.py
First step toward a more flexible tool abstraction for https://github.com/livekit/agents/issues/1966
Next steps are: support built-in OpenAI tools like web_search & add MCP support.
> support raw function descriptions 

- examples/voice_agents/basic_agent.py
- livekit-plugins/livekit-plugins-google/livekit/plugins/google/llm.py
- livekit-plugins/livekit-plugins-groq/livekit/plugins/groq/models.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/llm.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/models.py
- avoid concating None and string in Google LLM
- added llama 4 models to Cerebras & Groq
> Misc fixes

- livekit-agents/livekit/agents/llm/_strict.py
- livekit-agents/livekit/agents/llm/utils.py
- livekit-agents/livekit/agents/utils/connection_pool.py
- livekit-agents/livekit/agents/voice/generation.py
- also cleanup the function description given to the LLMs 
fix https://github.com/livekit/agents/issues/1987
Note that the LLM isn't aware of the default value, this context isn't added, it isn't supported by strict function descriptions.
Users need to add it on their function tool description if necessary
> support default arguments on function tools 

- livekit-agents/livekit/agents/voice/agent_activity.py
- livekit-agents/livekit/agents/voice/generation.py
- livekit-agents/livekit/agents/voice/io.py
- livekit-agents/livekit/agents/voice/transcription/synchronizer.py
https://linear.app/livekit/issue/AGT-1138/add-the-audio-synced-transcript-to-the-playbackfinishedevent
> store audio-synchronized transcript in chat_ctx when interrupted

- .github/next-release/changeset-c349be13.md
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/stt.py
> Revert "make semantic vad default for openai realtime and stt"

- .github/next-release/changeset-db8d9b3c.md
- examples/voice_agents/basic_agent.py
- livekit-plugins/livekit-plugins-google/livekit/plugins/google/beta/realtime/realtime_api.py
- livekit-plugins/livekit-plugins-google/livekit/plugins/google/utils.py
- livekit-plugins/livekit-plugins-google/pyproject.toml
- uv.lock
- resampling input according to spec
- buffering input to 50ms at a time
- fixed function output return dict
- cleanup to make code more readable
> improvements to Gemini Live handling

- .github/next-release/changeset-a6c0fcd6.md
- livekit-agents/livekit/agents/voice/room_io/room_io.py
1. check participant kinds in room io
2. set participant_identity from RoomInputOptions
> check participant kinds in room io

- livekit-agents/livekit/agents/voice/agent_activity.py
cancelling user code is the most confusing thing ever.. just happened to me...
> don't cancel user code on user_turn_completed 

- examples/voice_agents/fast-preresponse.py
- livekit-agents/livekit/agents/voice/__init__.py
- livekit-agents/livekit/agents/voice/agent_session.py
- livekit-agents/livekit/agents/voice/io.py
replaces https://github.com/livekit/agents/pull/2101
> add VideoSampler to AgentSession

- .github/next-release/changeset-ba3876d2.md
- livekit-plugins/livekit-plugins-google/livekit/plugins/google/beta/realtime/realtime_api.py
- livekit-plugins/livekit-plugins-google/pyproject.toml
- uv.lock
- https://ai.google.dev/gemini-api/docs/live#session-resumption
- https://ai.google.dev/gemini-api/docs/live#supported-languages
> support session resumption and language in gemini live

- livekit-agents/livekit/agents/llm/_strict.py
fix https://github.com/livekit/agents/issues/2186
> fix None default on function calls 

- .github/next-release/changeset-0c32e47c.md
- livekit-plugins/livekit-plugins-google/livekit/plugins/google/stt.py
fixes: https://github.com/livekit/agents/issues/2177
CC: @davidzhao @theomonnom
> google stt: allow configurable confidence score

- .github/next-release/changeset-816269c8.md
- livekit-plugins/livekit-plugins-google/livekit/plugins/google/stt.py
- livekit-plugins/livekit-plugins-google/livekit/plugins/google/tts.py
Some of the languages does not support streaming in google stt
StreamingRecognize does not support the "gu-IN" language code for the "chirp_2" model at location "us-central1"
+ better error logs
PTAL @theomonnom  @davidzhao
> google stt: support cofigurable streaming

- livekit-plugins/livekit-plugins-google/livekit/plugins/google/utils.py
fixes: https://github.com/livekit/agents/issues/2193
PTAL @davidzhao @theomonnom
> fix google llm: single enum value validation error

- livekit-plugins/livekit-plugins-google/livekit/plugins/google/stt.py
> correctly pass in spoken_punctuation param for Google STT

- livekit-plugins/livekit-plugins-google/livekit/plugins/google/beta/realtime/realtime_api.py
- livekit-plugins/livekit-plugins-google/livekit/plugins/google/utils.py
Vertex does not support id in function call responses, and their adapter does not handle this difference.
> fix Gemini Live function responses when using Vertex AI

- .github/next-release/changeset-be0cca68.md
- livekit-plugins/livekit-plugins-anthropic/livekit/plugins/anthropic/llm.py
- livekit-plugins/livekit-plugins-aws/livekit/plugins/aws/llm.py
- livekit-plugins/livekit-plugins-google/livekit/plugins/google/llm.py
> fix llm.chat for plugins when using with empty tools

- .github/next-release/changeset-440b34fa.md
- livekit-plugins/livekit-plugins-google/livekit/plugins/google/stt.py
Supress google stt stream timeout error when disconnecting/5 minutes timeout
PTAL @davidzhao @theomonnom
> supress stream timeout errors in google stt

- livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/tts.py
Somehow this was missed in cherrypicking to v1
PTAL @davidzhao @theomonnom
> [chore] use pool connection for deepgram tts in v1

- .github/next-release/changeset-d18231f7.md
- livekit-plugins/livekit-plugins-elevenlabs/livekit/plugins/elevenlabs/tts.py
> 11labs: improve resilience, do not fail when unexpected payload is received

- .github/next-release/changeset-2f3c00e4.md
- livekit-plugins/livekit-plugins-google/livekit/plugins/google/tts.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/tts.py
- uv.lock
this improves TTFB significantly compared to opus. In my tests it's about ~40% faster
> openai: switch to mp3 encoding by default

- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/llm.py
Add the `with_letta` convenience function for the OpenAI plugin. This allows developers to more easily integrate Letta with Livekit.
> feat: Add `with_letta` OpenAI plugin

- .github/next-release/changeset-0fc208ee.md
- livekit-plugins/livekit-plugins-google/livekit/plugins/google/beta/realtime/realtime_api.py
> handle missing token_count in realtime usage metrics

- .github/next-release/changeset-ffa7aeea.md
- livekit-plugins/livekit-plugins-google/livekit/plugins/google/llm.py
> google: do not error when empty responses are returned

- .github/next-release/changeset-abb19cef.md
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model.py
Resolves https://github.com/livekit/agents/issues/2312
> Add input_audio_noise_reduction to OpenAI RealtimeModel

- livekit-plugins/livekit-plugins-google/livekit/plugins/google/beta/realtime/realtime_api.py
- livekit-plugins/livekit-plugins-google/pyproject.toml
- uv.lock
we were sending Google NOT_GIVEN, which breaks the connection
> google: fix proactive audio config, update genai

- .github/next-release/changeset-21d5ddfe.md
- livekit-plugins/livekit-plugins-google/livekit/plugins/google/beta/realtime/realtime_api.py
fix https://github.com/livekit/agents/issues/2432
> fix gemini user transcription when tool calls

- livekit-plugins/livekit-plugins-assemblyai/livekit/plugins/assemblyai/__init__.py
- livekit-plugins/livekit-plugins-assemblyai/livekit/plugins/assemblyai/stt.py
- each word was a final transcript, which was rendering a new word per line in our frontend.
- follow the docs defaults
> fix AssemblyAI & follow docs

- livekit-agents/livekit/agents/voice/agent_activity.py
> use time.monotonic_ns for speech scheduling

- .github/workflows/tests.yml
- livekit-agents/pyproject.toml
- livekit-plugins/livekit-plugins-lmnt/README.md
- livekit-plugins/livekit-plugins-lmnt/livekit/plugins/lmnt/__init__.py
- livekit-plugins/livekit-plugins-lmnt/livekit/plugins/lmnt/models.py
- livekit-plugins/livekit-plugins-lmnt/livekit/plugins/lmnt/tts.py
- livekit-plugins/livekit-plugins-lmnt/livekit/plugins/lmnt/version.py
- livekit-plugins/livekit-plugins-lmnt/pyproject.toml
- pyproject.toml
- tests/docker-compose.yml
- tests/test_tts.py
This PR adds LMNT https://app.lmnt.com/ plugin as a TTS provider. 
- Added `livekit-plugins/livekit-plugins-lmnt`
- Added synthesis tests to `test_tts.py`
> LMNT agent plugin for TTS synthesis

- livekit-plugins/livekit-plugins-playai/livekit/plugins/playai/tts.py
Urgent fix for change which broke non-English TTS
> PlayAI plugin: fix language tag

- .github/next-release/changeset-1febe726.md
- livekit-plugins/livekit-plugins-aws/livekit/plugins/aws/llm.py
Collect prompt cached tokens count in llm usage in AWS LLM plugin
> Collect prompt cached tokens count in llm usage in AWS LLM plugin

- .github/next-release/changeset-b027afb9.md
- livekit-plugins/livekit-plugins-elevenlabs/livekit/plugins/elevenlabs/models.py
Add `eleven_v3` to tts elevenlabs plugin models
> add eleven labs v3 model

- livekit-plugins/livekit-plugins-cartesia/livekit/plugins/cartesia/stt.py
This should address #2564:
- Add input duration from frame duration values (similar to AssemblyAI)
- Send usage event when it is final
> add Cartesia STT usage event

- examples/voice_agents/push_to_talk.py
- livekit-agents/livekit/agents/stt/stream_adapter.py
- livekit-agents/livekit/agents/voice/agent_activity.py
- livekit-agents/livekit/agents/voice/agent_session.py
- livekit-agents/livekit/agents/voice/audio_recognition.py
- livekit-plugins/livekit-plugins-google/livekit/plugins/google/stt.py
fix https://github.com/livekit/agents/issues/2581
fix push to talk when using stt.StreamAdapter, slow STT and Google STT
> wait for final transcript in manual turn detection

- livekit-agents/livekit/agents/voice/room_io/_input.py
- livekit-agents/pyproject.toml
- uv.lock
10ms is unnecessary pressure on the asyncio event loop
> increase audio frame size 

- livekit-plugins/livekit-plugins-google/livekit/plugins/google/tts.py
This pull request adds optional SSML support to the Google TTS integration in LiveKit Agent.
Changes:
- Introduced a new `enable_ssml` option in the TTS class constructor.
- When `enable_ssml` is set to true, input text is wrapped in `<speak>...</speak>` tags and sent to the Google Text-to-Speech API as SSML.
- SSML is only applied to non-streaming TTS requests, as Google TTS does not support SSML in StreamingSynthesize.
Notes:
- The default behavior remains unchanged; plain text is used unless `enable_ssml` is explicitly set.
- Care should be taken to avoid enabling SSML with streaming requests, as this is not supported by the API and will result in an error.
> Add SSML support for Google TTS

- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model.py
fix https://github.com/livekit/agents/issues/2650
> fix tracing param in openai realtime

- .github/next-release/changeset-be014be1.md
- livekit-plugins/livekit-plugins-gladia/livekit/plugins/gladia/stt.py
fix https://github.com/livekit/agents/issues/2645
> raise error from gladia stt for fallback adapter and retry

- livekit-plugins/livekit-plugins-cartesia/livekit/plugins/cartesia/stt.py
- livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/stt.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/stt.py
- livekit-plugins/livekit-plugins-speechmatics/livekit/plugins/speechmatics/stt.py
fix https://github.com/livekit-examples/python-agents-examples/issues/19 and https://github.com/livekit/agents/pull/2643
> fix await tasks groups never return

- livekit-agents/livekit/agents/job.py
> chore: add note for job_context.api usage

- livekit-plugins/livekit-plugins-google/pyproject.toml
- uv.lock
> fix(google): update dependency versions

- livekit-agents/livekit/agents/voice/transcription/synchronizer.py
- livekit-plugins/livekit-plugins-google/livekit/plugins/google/beta/realtime/realtime_api.py
fix https://github.com/livekit/agents/issues/2644
> fix transcription sync warning when gemini no text output

- livekit-agents/livekit/agents/voice/agent_session.py
fix https://github.com/livekit/agents/issues/2690
> reset agent and user state after session closed

- livekit-plugins/livekit-plugins-inworld/README.md
Updating some links and the model name, by request from the Inworld team.
> Update Inworld README

- livekit-plugins/livekit-plugins-google/livekit/plugins/google/utils.py
- livekit-plugins/livekit-plugins-google/pyproject.toml
- uv.lock
https://github.com/googleapis/python-genai/releases/tag/v1.23.0
the async error was fixed
fix https://github.com/livekit/agents/issues/2729
> upgrade google genai to 1.23

- livekit-plugins/livekit-plugins-lmnt/README.md
* fix typo in header
* link to main website
* correct markdown to livekit docs
> Fix LMNT plugin docs

- livekit-agents/livekit/agents/voice/agent_activity.py
fix the order of the assistant message before a function tool
> fix assistant message order on the RunResult

- livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/stt.py
fix https://github.com/livekit/agents/issues/2802
> fix deepgram stt docs

- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/stt.py
fix https://github.com/livekit/agents/issues/2774#issuecomment-3032001493
> reset closing_ws for openai stt

- livekit-agents/livekit/agents/voice/chat_cli.py
This PR fixes the issue described in #2854.
> Prevent console mode from crashing

- livekit-agents/livekit/agents/voice/agent_activity.py
- livekit-agents/livekit/agents/voice/speech_handle.py
> fix unordered user messages

- examples/avatar_agents/audio_wave/agent_worker.py
- examples/avatar_agents/bey/agent_worker.py
- examples/minimal_worker.py
- examples/other/kokoro_tts.py
- examples/other/text_only.py
- examples/primitives/room_stats.py
- examples/voice_agents/annotated_tool_args.py
- examples/voice_agents/background_audio.py
- examples/voice_agents/basic_agent.py
- examples/voice_agents/dynamic_tool_creation.py
- examples/voice_agents/error_callback.py
- examples/voice_agents/fast-preresponse.py
- examples/voice_agents/gemini_video_agent.py
- examples/voice_agents/inactive_user.py
- examples/voice_agents/langgraph_agent.py
- examples/voice_agents/mcp/mcp-agent.py
- examples/voice_agents/multi_agent.py
- examples/voice_agents/push_to_talk.py
- examples/voice_agents/raw_function_description.py
- examples/voice_agents/realtime_load_chat_history.py
- examples/voice_agents/realtime_turn_detector.py
- examples/voice_agents/restaurant_agent.py
- examples/voice_agents/session_close_callback.py
- examples/voice_agents/silent_function_call.py
- examples/voice_agents/speedup_output_audio.py
- examples/voice_agents/structured_output.py
- examples/voice_agents/toggle_io.py
- examples/voice_agents/weather_agent.py
- examples/voice_agents/web_search.py
Explicitly calling ctx.connect() is not needed after 1.1.0 - https://github.com/livekit/agents/pull/2505
> Removing ctx.connect() from examples

- livekit-agents/livekit/agents/worker.py
> parameterize inference worker init timeout

- livekit-plugins/livekit-plugins-google/livekit/plugins/google/beta/realtime/realtime_api.py
fix the gemini model cannot be interrupted when using text modality with a TTS
> gemini: emit input_speech_started when new generation created

- examples/voice_agents/resume_interrupted_agent.py
- livekit-agents/livekit/agents/voice/agent_activity.py
- livekit-agents/livekit/agents/voice/events.py
- removed speech_id for now, I'm not sure about it, ideally users don't need to think about it
- renamed instructions to extra_instructions & added docs for it
> nit: update AgentFalseInterruptionEvent

- examples/voice_agents/langfuse_trace.py
- livekit-agents/livekit/agents/telemetry/traces.py
https://github.com/livekit/agents/issues/2260#issuecomment-3088961131
> add metadata when set tracer provider

- livekit-agents/livekit/agents/voice/speech_handle.py
- livekit-plugins/livekit-plugins-aws/livekit/plugins/aws/experimental/realtime/events.py
Add new voices from AWS. For a list of available voices, see: https://docs.aws.amazon.com/nova/latest/userguide/available-voices.html
> Update events.py with new AWS Nova Sonic voice

- livekit-plugins/livekit-plugins-inworld/livekit/plugins/inworld/tts.py
Someone at inworld sent me this bug fix after seeing it somewhere- posting it so it helps everyone :)
> Fixing chunk size bug on inworld plugin-- matches hume and neuphonic

- livekit-agents/livekit/agents/voice/agent_activity.py
- livekit-agents/livekit/agents/voice/speech_handle.py
fix https://github.com/livekit/agents/issues/3044
> fix using AgentTask in on_enter and on_ext

- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/models.py
Added 3 new models: 
- gpt-5 
- gpt-5-mini
- gpt-5-nano
> feat: add openai gpt-5 models

- livekit-plugins/livekit-plugins-baseten/livekit/plugins/baseten/llm.py
- livekit-plugins/livekit-plugins-baseten/livekit/plugins/baseten/models.py
- livekit-plugins/livekit-plugins-groq/livekit/plugins/groq/models.py
- livekit-plugins/livekit-plugins-groq/livekit/plugins/groq/services.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/llm.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/models.py
- livekit-plugins/livekit-plugins-openai/pyproject.toml
- uv.lock
also added compatibility with gpt-oss across providers
> expose reasoning_effort and other new params.

- livekit-agents/livekit/agents/voice/audio_recognition.py
- livekit-plugins/livekit-plugins-turn-detector/livekit/plugins/turn_detector/base.py
- livekit-plugins/livekit-plugins-turn-detector/livekit/plugins/turn_detector/multilingual.py
- handles errors gracefully
- avoids sending system messages, images, and audio
- truncates messages prior to sending
> fix: improved handling for remote inference

- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/llm.py
fix https://github.com/livekit/agents/issues/3114
> fix: remove tool_choice when no tools provided

- .github/workflows/tests.yml
- tests/test_agent_session.py
needs https://github.com/livekit/agents/pull/3123 to pass the test
> add unit tests for preemptive generation

- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/llm.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/utils.py
some cerebras models don't support strict tool schema with error `Tools with strict=True are not supported by this model`
> use non-strict tool schema for cerebras llm

- livekit-agents/livekit/agents/llm/_provider_format/mistralai.py
- livekit-plugins/livekit-plugins-mistralai/livekit/plugins/mistralai/__init__.py
- livekit-plugins/livekit-plugins-mistralai/livekit/plugins/mistralai/llm.py
- livekit-plugins/livekit-plugins-mistralai/livekit/plugins/mistralai/models.py
- livekit-plugins/livekit-plugins-mistralai/livekit/plugins/mistralai/stt.py
- livekit-plugins/livekit-plugins-mistralai/pyproject.toml
the original mistralai plugin doesn't work, and doesn't support tool calls.
> fix mistralai llm and stt

- livekit-plugins/livekit-plugins-smallestai/README.md
- livekit-plugins/livekit-plugins-smallestai/livekit/plugins/smallestai/__init__.py
- livekit-plugins/livekit-plugins-smallestai/livekit/plugins/smallestai/log.py
- livekit-plugins/livekit-plugins-smallestai/livekit/plugins/smallestai/models.py
- livekit-plugins/livekit-plugins-smallestai/livekit/plugins/smallestai/tts.py
- livekit-plugins/livekit-plugins-smallestai/livekit/plugins/smallestai/version.py
- livekit-plugins/livekit-plugins-smallestai/pyproject.toml
Added support for [Smallest AI](https://smallest.ai/) TTS Plugin
> support for smallest.ai tts plugin

- livekit-plugins/livekit-plugins-google/livekit/plugins/google/beta/realtime/realtime_api.py
some gemini live models return a `output_transcription.finished` and `turn_complete` message after a tool call while some don't.
we will close the generation right after a tool call, those flags will create a new generation and interrupt the tool execution.
> gemini live: create new generation only if response has a content

- livekit-agents/livekit/agents/voice/agent_activity.py
related to https://github.com/livekit/agents/pull/2095
> fix interruption context when speech has't started for session.say

- livekit-plugins/livekit-plugins-google/livekit/plugins/google/llm.py
fix https://github.com/livekit/agents/issues/3201
> remove thinking_budget range check for google LLM

- livekit-agents/livekit/agents/ipc/inference_proc_lazy_main.py
- livekit-agents/livekit/agents/ipc/job_proc_lazy_main.py
no longer needed with the new CLI
> remove custom excepthook

- livekit-plugins/livekit-plugins-anthropic/livekit/plugins/anthropic/models.py
This PR...
- removes retired models,
- adds comment to deprecated models,
- adds all currently active models and
- adds URL to Anthropic's "Model deprecations" page.
> Update Anthropic LLM models

- livekit-agents/pyproject.toml
- pyproject.toml
previously it required <5, which isn't necessary
> chore: allow types-protobuf>=4

- livekit-agents/livekit/agents/voice/agent_activity.py
- livekit-agents/livekit/agents/voice/agent_session.py
- livekit-agents/livekit/agents/voice/speech_handle.py
For some speeches that cannot be interrupted by voice but are expected to be interrupted by the program, the force field will be very useful.
> feat: add force parameter to interrupt methods for speech generation

- livekit-agents/livekit/agents/voice/agent_session.py
- tests/test_evals.py
fix https://github.com/livekit/agents/issues/3149
```python
result = await sess.start(EchoAgent(), capture_run=True)
assert result is not None
result.expect.next_event().is_agent_handoff(new_agent_type=EchoAgent)
result.expect.next_event().is_message(role="assistant")
```
> add capture_run for AgentSession.start

- .github/workflows/ci.yml
- examples/voice_agents/ultravox_realtime_api.py
- livekit-agents/pyproject.toml
- livekit-plugins/livekit-plugins-google/livekit/plugins/google/beta/realtime/realtime_api.py
- livekit-plugins/livekit-plugins-google/livekit/plugins/google/llm.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model.py
- livekit-plugins/livekit-plugins-ultravox/examples/agent.py
- livekit-plugins/livekit-plugins-ultravox/livekit/plugins/ultravox/__init__.py
- livekit-plugins/livekit-plugins-ultravox/livekit/plugins/ultravox/models.py
- livekit-plugins/livekit-plugins-ultravox/livekit/plugins/ultravox/realtime/__init__.py
- livekit-plugins/livekit-plugins-ultravox/livekit/plugins/ultravox/realtime/events.py
- livekit-plugins/livekit-plugins-ultravox/livekit/plugins/ultravox/realtime/realtime_model.py
- livekit-plugins/livekit-plugins-ultravox/livekit/plugins/ultravox/utils.py
- livekit-plugins/livekit-plugins-ultravox/livekit/plugins/ultravox/version.py
- pyproject.toml
a follow up of https://github.com/livekit/agents/pull/2992, close https://github.com/livekit/agents/issues/1378
needs https://github.com/livekit/agents/pull/3334 for better transcription forwarding
limitations:
- Ultravox API returns the text sent via `session.generate_reply()` as user transcript again
- `instructions` of generate_reply is sent as user text with `<instruction>...</instruction>` tag
> fix and clean ultravox realtime API plugin

- livekit-plugins/livekit-plugins-elevenlabs/livekit/plugins/elevenlabs/tts.py
replace https://github.com/livekit/agents/pull/3336, fix https://github.com/livekit/agents/issues/3330
> add preferred_alignment and fix alignment chars

- livekit-agents/livekit/agents/voice/transcription/synchronizer.py
AgentSession.aclose may hang when the output is paused because the transcription synchronizer is not properly closed
> fix transcription synchronizer cannot be closed if paused

- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/utils.py
> fix(openai): correctly handle update_options for active sessions

- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/utils.py
fix https://github.com/livekit/agents/issues/3449
> fix openai realtime with azure when input_audio_noise_reduction is not given

- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/utils.py
fix https://github.com/livekit/agents/issues/3445#issuecomment-3306736804
> fix oai realtime options with default null

- livekit-plugins/livekit-plugins-silero/livekit/plugins/silero/vad.py
fix https://github.com/livekit/agents/issues/3442
> fix silero vad speech_buffer_max_reached

- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/utils.py
updated type for noise reduction, users can pass in a string or `NoiseReduction(type=...) `
> fixed noise reduction type

- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model.py
> return RealtimeModelBeta for Azure OpenAI Realtime

- livekit-agents/livekit/agents/llm/llm.py
- livekit-agents/livekit/agents/llm/realtime.py
- livekit-agents/livekit/agents/metrics/base.py
- livekit-agents/livekit/agents/metrics/utils.py
- livekit-agents/livekit/agents/telemetry/utils.py
- livekit-agents/livekit/agents/voice/room_io/room_io.py
- livekit-plugins/livekit-plugins-aws/livekit/plugins/aws/experimental/realtime/realtime_model.py
- livekit-plugins/livekit-plugins-baseten/livekit/plugins/baseten/stt.py
- livekit-plugins/livekit-plugins-google/livekit/plugins/google/beta/realtime/realtime_api.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model_beta.py
- livekit-plugins/livekit-plugins-sarvam/livekit/plugins/sarvam/stt.py
- livekit-plugins/livekit-plugins-ultravox/livekit/plugins/ultravox/realtime/realtime_model.py
fix conflicts between #3165 and #3439, #3456
> fix conflicts of metrics.metadata

- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model_beta.py
fix https://github.com/livekit/agents/issues/3483
> fix ttft for OpenAI realtime model

- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model_beta.py
fix https://github.com/livekit/agents/issues/3504
> fix OAI realtime: remove deepcopy when reconnection

- livekit-agents/livekit/agents/voice/avatar/_datastream_io.py
same issue as https://github.com/livekit/agents/pull/3473 for clear buffer RPC call, fix https://github.com/livekit/agents/issues/3510
> fix datastream io clear buffer rpc for thread executor

- livekit-plugins/livekit-plugins-gladia/livekit/plugins/gladia/stt.py
- **Added support for partial transcriptions** when the interim_results parameter is enabled.
- **Enhanced debugging capabilities** by including the LiveKit version in the configuration sent to Gladia.
> Gladia STT: support partial transcriptions

- livekit-agents/livekit/agents/voice/agent_session.py
flexibility for draining tasks/activity
> added drain param to session.shutdown()

- livekit-agents/livekit/agents/voice/audio_recognition.py
fix https://github.com/livekit/agents/issues/3558
> fix stt final transcript triggers user turn in manual turn detection

- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model.py
- livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model_beta.py
enable retry when connection failed due to network issue
> handle aiohttp client error when connecting to openai realtime api

- examples/voice_agents/realtime_joke_teller.py
- livekit-plugins/livekit-plugins-aws/pyproject.toml
fix https://github.com/livekit/agents/issues/3590
> fix aws realtime deps version
