livekit/agents

livekit-agents/livekit/agents/stt/stt.py
livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/stt.py

Notes: 
- Added `speech_final` to `SpeechEvent`. Defaulted to `False` because looks like it's being used elsewhere. 
- Return `speech_final` for each `SpeechEvent`. 
- Add `utterance_end_ms` for more control over VAD
Relevant Docs:
https://developers.deepgram.com/docs/understanding-end-of-speech-detection 
https://developers.deepgram.com/docs/understand-endpointing-interim-results

Update deepgram endpointing 

---

.github/workflows/ruff.yml
examples/fal/game_state.py
examples/kitt/kitt.py
livekit-agents/livekit/agents/worker.py
livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/stt.py
livekit-plugins/livekit-plugins-google/livekit/plugins/google/stt.py
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/stt.py
ruff.toml
tests/test_stt.py

Tested with KITT. It significantly improves the end of speech behavior so that we are giving it a 1s wait before starting to process user input.

Update KITT and other plugins to use end_of_speech field

---

livekit-plugins/livekit-plugins-elevenlabs/livekit/plugins/elevenlabs/tts.py
livekit-plugins/livekit-plugins-elevenlabs/livekit/plugins/elevenlabs/version.py

Elevenlabs closes websockets when you don't send text fast enough. We would currently drop that text and short circuit out of the `task_done()` call.

Retry text that failed to send to elevenlabs + fix skipped task_done() call

---

examples/agent-quickstart/painter.py
examples/fal/fal.py
examples/kitt/kitt.py

There was changes made to `rtc.AudioStream` and `rtc.VideoStream` to return an FrameEvent object instead of the Frame in this pull request https://github.com/livekit/python-sdks/pull/155. This causes issues in the livekit examples as they are still expecting a Frame object and then throws an error that the attribute `remix_and_resample` doesn't exist on the object.
I've updated all examples impacted by this change.

fixes audio and video frame events in examples

---

livekit-agents/livekit/agents/codecs/mp3.py
livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/stt.py
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/tts.py
tests/test_stt.py

- make the mp3 decoder synchronous
- deepgram APIs are pretty annoying. Everything seems to have its own brain:
- speechstarted doesn't care about speech_final or utterance end
- utterance end doesn't care if there were any transcripts with non-empty text.
- I'm accounting for them in this PR now. This keeps our API such that START is always matched with END even though deepgram doesn't do that.

Make mp3 decoder synchronous + Deepgram Tweaks

---

livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/stt.py

Uses default sample rate and original audio without resampling sample for depgram live stream
This addresses the issue highlighted here:
https://github.com/livekit/agents/issues/202

Uses default sample rate and original audio without resampling

---

examples/voice-assistant/minimal_assistant.py
livekit-agents/livekit/agents/cli/cli.py
livekit-agents/livekit/agents/ipc/job_main.py
livekit-agents/livekit/agents/transcription/tts_forwarder.py
livekit-agents/livekit/agents/voice_assistant/assistant.py
livekit-agents/livekit/agents/voice_assistant/plotter.py

- remove annoying logs about slow tasks (now default to 2s before logging)
- correct fix would be the prewarming stuff with processes
- (in debug mode, this is set to 50ms)
- VAD is now the source of truth for both, interruption and answers validation
- fix tts_forwarder graceful shutdown

voice assistant tweaks

---

livekit-agents/livekit/agents/voice_assistant/assistant.py

Perhaps this was done intentionally (?), but there is a potential race condition (which I've encountered) where the callback to, say, `_on_track_subscribed` comes immediately after `self._on_track_subscribed()`, but before `self._linked_participant = identity` in the `voice_assistant/_link_participant()` function. This simply moves the assignment before the callbacks are registered.

voice_assistant: fix _linked_participant race

---

examples/_deployed/kitt/kitt.py

With the baked-in latency everywhere else in the pipeline. 500ms should be more than enough time for clients to subscribe to audio tracks.

Reduce the initial sleep

---

examples/_deployed/kitt/requirements.txt
examples/simple-color/requirements.txt
examples/speech-to-text/requirements.txt
examples/text-to-speech/requirements.txt
examples/voice-assistant/minimal_assistant.py
examples/voice-assistant/requirements.txt
livekit-agents/livekit/agents/version.py
livekit-plugins/livekit-plugins-azure/livekit/plugins/azure/version.py
livekit-plugins/livekit-plugins-azure/setup.py
livekit-plugins/livekit-plugins-cartesia/livekit/plugins/cartesia/version.py
livekit-plugins/livekit-plugins-cartesia/setup.py
livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/version.py
livekit-plugins/livekit-plugins-deepgram/setup.py
livekit-plugins/livekit-plugins-elevenlabs/livekit/plugins/elevenlabs/version.py
livekit-plugins/livekit-plugins-elevenlabs/setup.py
livekit-plugins/livekit-plugins-google/livekit/plugins/google/version.py
livekit-plugins/livekit-plugins-google/setup.py
livekit-plugins/livekit-plugins-nltk/livekit/plugins/nltk/version.py
livekit-plugins/livekit-plugins-nltk/setup.py
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/version.py
livekit-plugins/livekit-plugins-openai/setup.py
livekit-plugins/livekit-plugins-silero/livekit/plugins/silero/version.py
livekit-plugins/livekit-plugins-silero/setup.py

- livekit-agents==v0.7.2
- livekit-plugins-openai==v0.6.0
- livekit-plugins-elevenlabs==v0.6.0
- livekit-plugins-silero==v0.5.1
- livekit-plugins-deepgram==v0.5.1
- livekit-plugins-google==v0.5.1
- livekit-plugins-cartesia==v0.1.1
- livekit-plugins-azure==v0.2.1
- livekit-plugins-nltk==v0.6.1
also removed unused dependencies

bump versions

---

livekit-agents/livekit/agents/cli/protocol.py
livekit-agents/livekit/agents/worker.py
livekit-agents/setup.py

This bug prevented reloaded agents from publishing transcriptions and from updating room metadata. 
Cause: The SFU does more than set video grants when generating tokens: https://github.com/livekit/protocol/blob/main/agent/token.go and it has apis that are not available in the client library. (i.e. SetKind)
Fix: In reloaded jobs now we simply reuse the previous token and extend its expiration.

Fix token on job reload in dev mode

---

livekit-agents/livekit/agents/stt/stream_adapter.py
livekit-agents/livekit/agents/vad.py
livekit-agents/livekit/agents/voice_assistant/assistant.py
livekit-agents/livekit/agents/voice_assistant/plotter.py
livekit-plugins/livekit-plugins-silero/livekit/plugins/silero/__init__.py
livekit-plugins/livekit-plugins-silero/livekit/plugins/silero/onnx_model.py
livekit-plugins/livekit-plugins-silero/livekit/plugins/silero/resources/.gitattributes
livekit-plugins/livekit-plugins-silero/livekit/plugins/silero/resources/__init__.py
livekit-plugins/livekit-plugins-silero/livekit/plugins/silero/resources/silero_vad.onnx
livekit-plugins/livekit-plugins-silero/livekit/plugins/silero/vad.py
livekit-plugins/livekit-plugins-silero/setup.py
tests/test_stt.py
tests/utils.py

- remove pytorch dependency
- we only use onnxruntime now (avg size of onnxruntime is 7MB, silero model is 1.5MB)
- use right window sizes (enforce the same one used while training the model)
- allow 16Khz*X sample rates (not technically right, we sample each sr//16000 step)
- fixed warning when loading the silero model
- the model is now embedded inside the pypi package
- move vad paramters to silero.VAD constructor
- fix duplicate final transcripts on the stt.StreamAdapter 
EDIT: the tests should now be fixed

rework silero vad

---

livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/stt.py

Based on the docs linked, it seems like Deepgram will withhold a transcript, which causes issues if you rely on Deepgram events for end of speech detection.
https://developers.deepgram.com/docs/smart-format (at the bottom)

expose Deepgram's no_delay for smart formatting

---

livekit-plugins/livekit-plugins-silero/setup.py

See also https://iscinumpy.dev/post/bound-version-constraints/

Allow use with numpy>=2

---

livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/tts.py

This PR adds support for speed param when calling OpenAI TTS
Ref: https://platform.openai.com/docs/api-reference/audio/createSpeech#audio-createspeech-speed

Support speed param when calling openai TTS

---

livekit-plugins/livekit-plugins-minimal/README.md
livekit-plugins/livekit-plugins-minimal/livekit/plugins/minimal/__init__.py
livekit-plugins/livekit-plugins-minimal/livekit/plugins/minimal/version.py
livekit-plugins/livekit-plugins-minimal/pyproject.toml
livekit-plugins/livekit-plugins-minimal/setup.py

livekit-plugins-minimal

---

README.md

The command to connect to an existing room has changed to `connect` but the documentation is still referring to the old command `simulate-job`.

Update README.md simulate job command

---

.github/workflows/publish-package.yml
livekit-plugins/livekit-plugins-minimal/README.md

Previously we had package names defined as `livekit-plugins/livekit-plugin-NAME`. 
In order for changesets to work properly the package names have to be formatted in a npm compliant way. 
This is why I changed the name pattern to `livekit-plugin-NAME`. This has the advantage to be aligned with the pypi package names. 
Due to this change the way we define the CWD of the build job needs to change. 
Instead of relying on the package name as a path equivalent (which we did with the `livekit-plugins/livekit-plugin-NAME` pattern), we instead introduce the convention that all `livekit-plugin-NAME` packages live within the `livekit-plugins` folder. 
This is pretty reasonable, I think, and allows us to construct the CWD directly from the package name.

Fix module name usage in action

---

.github/workflows/publish-package.yml

@theomonnom handled the parallel git upload issue already by adding `--rebase --autostash` to the commit step.

Remove max parallel setting for release action

---

livekit-agents/livekit/agents/utils/http_context.py

Some users are using the plugins by themselves without the agent subprocess/worker code. In these cases, a global http_session is never created. IMO this use case is perfectly legitimate.

Lazy create http session if needed

---

livekit-plugins/livekit-plugins-google/livekit/plugins/google/tts.py

Google tts.py doesn't support streaming

---

.changeset/modern-geese-applaud.md
livekit-agents/livekit/agents/job.py

was seeing this warning in my agent logs when running the `examples/voice-assistant/minimal_assistant.py` example:
```bash
/Users/nabil/repos/livekit-test/.venv/lib/python3.12/site-packages/livekit/rtc/_event_emitter.py:14: RuntimeWarning: coroutine '_apply_auto_subscribe_opts.<locals>.on_track_published' was never awaited
callback(*args, **kwargs)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```
making function synchronous resolved this, as _subcribe_if_needed() does not need to be async.
---
I no longer see any warnings in my agent logs after this change.

remove unnecessary async function

---

.changeset/red-numbers-complain.md
livekit-plugins/livekit-plugins-silero/livekit/plugins/silero/onnx_model.py

onnx runtime had allow_spinning enabled, and it was using resources where it shouldn't be.
correctly disabling `allow_spinning` to significantly reduce resource consumption

silero: fix high cpu usage

---

.changeset/violet-students-shout.md
livekit-plugins/livekit-plugins-elevenlabs/livekit/plugins/elevenlabs/tts.py

will now output the following and skip synthesis instead of attempting to process data as PCM:
```
2024-08-02 12:01:38,006 - ERROR livekit.plugins.elevenlabs - 11labs returned non-PCM data: {"detail":{"status":"invalid_api_key","message":"Invalid API key"}} {"pid": 59945, "job_id": "AJ_5oARRaVErZCW"}
```

elevenlabs: error on non-PCM data

---

.changeset/empty-rings-begin.md
livekit-agents/livekit/agents/voice_assistant/voice_assistant.py

If a user speaks slowly or trails off a bit we are finding that Deepgram will return multiple chunks of "final" transcripts, which are concatenated without a space creating things like this:
> Yeah. I mean, I I haven't packedyet at all, but she's got, Harry all packed up, so that's the most important part.Know,
(Notice lack of space between "packed" and "yet" and before "Know")

fix(voice assistant): missing spaces between transcript chunks

---

.changeset/unlucky-starfishes-fold.md
livekit-agents/livekit/agents/voice_assistant/voice_assistant.py
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/stt.py
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/tts.py

os.path.join uses backslash on windows. the appropriate fnc to use is urllib.parse.urljoin

openai: fix incorrect API urls on Windows

---

.changeset/khaki-gorillas-cross.md
livekit-plugins/livekit-plugins-elevenlabs/livekit/plugins/elevenlabs/models.py
livekit-plugins/livekit-plugins-elevenlabs/livekit/plugins/elevenlabs/tts.py

This model should have a faster inference time (the first time to first frame didn't really reduced tho)

elevenlabs: update default model to eleven_turbo_v2_5

---

.changeset/angry-drinks-hunt.md
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/llm.py
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/tts.py

this was blocking people using another provider (using the base_url) and openai at the same time. (The key could only be specified using the OPENAI_API_KEY envvar)

openai: add api_key argument

---

.changeset/cool-olives-act.md
livekit-agents/setup.py

> For speeding up DNS resolving by client API you may install [aiodns](https://docs.aiohttp.org/en/stable/glossary.html#term-aiodns) as well. This option is highly recommended:
https://docs.aiohttp.org/en/stable/
> aiohttp.DefaultResolver by default (asynchronous if aiodns>=1.1 is installed).
> The resolver is aiohttp.ThreadedResolver by default, asynchronous version is pretty robust but might fail in very rare cases.
https://docs.aiohttp.org/en/stable/client_reference.html
This will use the async resolver instead of aiohttp.ThreadedResolver by default (recommended by aiohttp)

use aiodns resolver by default

---

.changeset/sharp-hornets-talk.md
livekit-agents/livekit/agents/voice_assistant/voice_assistant.py

This could happens when using function calling with the VoiceAssistant.say method

voiceassistant: fix AssertionError when there is no user_question

---

.changeset/warm-kiwis-cover.md
livekit-plugins/livekit-plugins-elevenlabs/livekit/plugins/elevenlabs/tts.py

11labs API requires `style` float and `use_speaker_boost` boolean. defaulting to None gets translated to JSON as `null` type. this sets them to their default values noted in the API here: https://api.elevenlabs.io/v1/voices/settings/default

Fix elevenlabs voice settings breaking

---

.changeset/breezy-tigers-cover.md
livekit-agents/livekit/agents/llm/function_context.py

Example:
```
@llm.ai_callable(description="Update the user information")
async def update_user_info(
self,
name: str | None = None
email: str | None = None
):
...
```

add support for optional arguments on ai_callable functions

---

examples/text-to-speech/sync_tts_transcription.py

https://livekit-users.slack.com/archives/C01KVTJH6BX/p1723198697156069?thread_ts=1722507759.754139&cid=C01KVTJH6BX

examples/text-to-speech/sync_tts_transcription.py: add `.end_input()` after `.flush()`

---

.changeset/lazy-cups-cross.md
livekit-agents/livekit/agents/ipc/proc_pool.py
livekit-agents/livekit/agents/ipc/supervised_proc.py

- avoid stressing the OS too much

limit simultaneous process initialization

---

.changeset/stale-pots-enjoy.md
livekit-agents/livekit/agents/llm/_oai_api.py
livekit-agents/livekit/agents/llm/function_context.py
tests/test_llm.py

- also attempt to fix flaky llm tests 
- store choices as tuple instead of a list (list in the TypeInfo constructor is still supported for backward compatibility)

llm: fix optional arguments & non-hashable list

---

livekit-plugins/livekit-plugins-browser/cef/CMakeLists.txt
livekit-plugins/livekit-plugins-browser/cef/src/CMakeLists.txt
livekit-plugins/livekit-plugins-browser/cef/src/agents_python.cpp
livekit-plugins/livekit-plugins-browser/cef/src/agents_python.hpp
livekit-plugins/livekit-plugins-browser/cef/src/app.cpp
livekit-plugins/livekit-plugins-browser/cef/src/app.hpp
livekit-plugins/livekit-plugins-browser/cef/src/app_mac.mm
livekit-plugins/livekit-plugins-browser/cef/src/dev_renderer.cpp
livekit-plugins/livekit-plugins-browser/cef/src/dev_renderer.hpp
livekit-plugins/livekit-plugins-browser/cef/src/gleq.h
livekit-plugins/livekit-plugins-browser/cef/src/handler.cpp
livekit-plugins/livekit-plugins-browser/cef/src/handler.hpp
livekit-plugins/livekit-plugins-browser/cef/src/keyboard_codes.h

livekit-plugins-browser: handle mouse/keyboard inputs on devmode 

---

.changeset/metal-zebras-kick.md
livekit-agents/livekit/agents/ipc/proc_pool.py
livekit-agents/livekit/agents/worker.py

untested, SFU hasn't implemented JobTermination yet

Add ServerMessage.termination handler

---

livekit-plugins/livekit-plugins-anthropic/livekit/plugins/anthropic/llm.py
livekit-plugins/livekit-plugins-azure/livekit/plugins/azure/stt.py
livekit-plugins/livekit-plugins-azure/livekit/plugins/azure/tts.py
livekit-plugins/livekit-plugins-cartesia/livekit/plugins/cartesia/tts.py
livekit-plugins/livekit-plugins-clova/livekit/plugins/clova/stt.py
livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/stt.py
livekit-plugins/livekit-plugins-elevenlabs/livekit/plugins/elevenlabs/tts.py
livekit-plugins/livekit-plugins-google/livekit/plugins/google/stt.py
livekit-plugins/livekit-plugins-google/livekit/plugins/google/tts.py
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/llm.py
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/stt.py
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/tts.py

also provide envvar shims for openai.LLM alt providers
<code>``</code> means "inline code" in reStructuredText

plugins: add docstrings explaining API keys

---

.changeset/pink-ducks-complain.md
livekit-agents/livekit/agents/job.py

Improves devex to allow participant entrypoints to be defined at the top level

Pass context into participant entrypoint

---

.changeset/tender-bikes-dream.md
livekit-plugins/livekit-plugins-google/README.md
livekit-plugins/livekit-plugins-google/livekit/plugins/google/stt.py
livekit-plugins/livekit-plugins-google/setup.py

Enable the use of the Google TTS plugin via application default
credentials, where no credential info is provided explicitly,
and instead is default via the default resolution order.
This enables two other common configurations including
deployment on Google Cloud where application
credentials are injected via the VM Metadata Service or on
developer systems where credentials are stored at
`~/.config/gcloud/application_default_credentials.json`
without setting the `GOOGLE_APPLICATION_CREDENTIALS`
environment variable.

Enable Google TTS with application default credentials

---

.changeset/afraid-dolls-enjoy.md
livekit-agents/livekit/agents/utils/aio/__init__.py
livekit-plugins/livekit-plugins-google/livekit/plugins/google/stt.py

this shouldn't await the task itself

improve gracefully_cancel logic

---

livekit-agents/livekit/agents/cli/log.py

the root logger was in warning mode to avoid noisy logs.
we know keep a list of noisy loggers instead and put them to warn if the user didn't specify any level yet

limit noisy logs & keep the root logger info

---

.changeset/moody-doors-poke.md
livekit-agents/livekit/agents/voice_assistant/voice_assistant.py

When playing the Agent's speech, if the user interrupts, the while loop here will become an infinite loop and needs to be exited when interrupted.

Fix the problem of infinite loop when agent speech is interrupted

---

.changeset/fresh-mayflies-shout.md
examples/multimodal_agent.py
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model.py

Solves #827.
In `realtime_model.py`, tool call outputs (`message_content`) are not strings by the time they reach the assertion `assert isinstance(message_content, str)`. 
This PR handles tool calls before other message types, which depend on `message_content` being a list. You can also just replace `message_content` with `message.content`, and keep the original order— both fixes work.
Tested according to the [minimal Multimodel Agent + Function calling example here](https://docs.livekit.io/agents/voice-agent/function-calling/).
Also: extraordinary work, Livekit team! Thank you for everything you do. ❤️ and ofc no need to solve it this way / merge if there's another fix you're working on.

Fix tool call output type error

---

.changeset/popular-needles-kiss.md
livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/stt.py

Deepgram supports `profanity_filter` which recognizes profanity and converts it to the nearest recognized non-profane word or removes it from the transcript completely.
https://developers.deepgram.com/docs/profanity-filter
Adds support for this option in `STTOptions` and forwards the option in the live_config

add(plugin/deepgram): accepts parameter profanity_filter

---

.changeset/cold-kings-accept.md
livekit-agents/livekit/agents/pipeline/agent_playout.py
livekit-agents/package.json

I believe this fixes https://github.com/livekit/agents/issues/825
The problem seems to be we get occasional empty audio frames which causes freezes.

Make sure there is some queued duration before waiting for audio playout

---

livekit-agents/livekit/agents/cli/cli.py
livekit-agents/livekit/agents/cli/proto.py
livekit-agents/livekit/agents/worker.py

Give a warning when config for load threshold is invalid.
```
{"message": "load_threshold in prod env must be less than 1, current value: 2", "level": "WARNING", "name": "livekit.agents", "timestamp": "2024-10-12T08:20:02.168613+00:00"}
```
This pr is for issue https://github.com/livekit/agents/issues/884

warning incorrect threshold config

---

livekit-plugins/livekit-plugins-azure/livekit/plugins/azure/tts.py

In this PR, I have added support for SSML prosody tags in Azure TTS. This will allow users to control the speech rate, pitch, and volume of the generated speech. The prosody tag is a part of the SSML specification and is supported by Azure TTS.
To use the prosody tags in Azure TTS component the user needs to provide a `ProsodyConfig` object to the `TTS` component. 
The `ProsodyConfig` is validated in the `TTS` component.
```python
@dataclass
class ProsodyConfig:
"""
Prosody configuration for Azure TTS.
Args:
rate: Speaking rate. Can be one of "x-slow", "slow", "medium", "fast", "x-fast", or a float. A float value of 1.0 represents normal speed.
volume: Speaking volume. Can be one of "silent", "x-soft", "soft", "medium", "loud", "x-loud", or a float. A float value of 100 (x-loud) …
```

Azure TTS Prosody SSML support

---

.changeset/heavy-donkeys-check.md
livekit-agents/livekit/agents/pipeline/agent_output.py
livekit-agents/livekit/agents/pipeline/pipeline_agent.py

If you said agent.say(), but your before_tts_cb returned an AsyncIterable, it'd throw - because the transcript was a string but the before_tts_cb was AsyncIterable.

Fix bug with before_tts_cb when speech is string but before_tts_cb returns async iterable

---

.changeset/lucky-kangaroos-fly.md
livekit-plugins/livekit-plugins-azure/livekit/plugins/azure/tts.py

This pull request addresses a validation issue within the ProsodyConfig class for Azure Text-to-Speech (TTS) in the livekit-plugins/livekit-plugins-azure/livekit/plugins/azure/tts.py file.
- Corrected the default value for volume from "x-loud" to None.
- Fixed the validation logic for rate by adding type checks and ensuring the value is one of the specified literals or within the valid float range.
- Updated the validation for volume to include type checks.
- Ensured volume is validated against the correct list of literals if it's a string type.

Fixed Prosody Config Validation

---

.changeset/short-boxes-smoke.md
.github/workflows/tests.yml
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/llm.py
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/stt.py
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/tts.py

fix ridiculously low timeouts
future work would be to expose those in every client we have
fix https://github.com/livekit/agents/issues/807

openai: fix low timeouts 

---

.changeset/soft-apples-itch.md
livekit-agents/livekit/agents/pipeline/pipeline_agent.py

nested function calls result in no answer from the agent. Some LLMs of different providers may hallucinate a function call

avoid nested function calls

---

.changeset/nice-icons-watch.md
livekit-agents/livekit/agents/pipeline/pipeline_agent.py

https://github.com/livekit/agents/issues/958#issue-2600681919

Fixed a problem that before_llm_cb return value is not canceled even if False when the return value is coroutine.

---

.changeset/chilly-tables-speak.md
livekit-agents/livekit/agents/worker.py

the thread could start and then lock would be undefined, and you'd get the occasional
`AttributeError: '_DefaultLoadCalc' object has no attribute '_lock'`

Fix race in default load calc.

---

.changeset/serious-worms-tap.md
livekit-agents/livekit/agents/ipc/job_main.py

We would see stack traces when rooms exited:
```
--- Logging error ---
Traceback (most recent call last):
File "/Users/martin/Library/Caches/pypoetry/virtualenvs/agent-x_OPPxuI-py3.12/lib/python3.12/site-packages/livekit/agents/ipc/job_main.py", line 52, in emit
record = copy.copy(record)
^^^^^^^^^^^^^^^^^
File "/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/copy.py", line 87, in copy
rv = reductor(4)
^^^^^^^^^^^
ImportError: sys.meta_path is None, Python is likely shutting down
Call stack:
File "/Users/martin/Library/Caches/pypoetry/virtualenvs/agent-x_OPPxuI-py3.12/lib/python3.12/site-packages/aiohttp/client.py", line 425, in __del__
self._loop.call_exception_handler(context)
File …
```

fix shutdown error stack trace

---

.changeset/proud-wombats-perform.md
livekit-agents/livekit/agents/multimodal/agent_playout.py
livekit-agents/livekit/agents/multimodal/multimodal_agent.py

- Expose the `user_speech_committed`, `agent_speech_committed`, and `agent_speech_interrupted` for multimodal agents
- Emit `user_started_speaking` and `user_stopped_speaking` for multimodal agents
- Fixed a bug that `handle._tr_fwd` of multimodal agents cannot be closed for some interruption cases
Related to: https://github.com/livekit/agents/issues/877

feat: expose user_speech_committed and agent_speech_committed for multimodal agents

---

.changeset/heavy-turtles-rule.md
livekit-agents/livekit/agents/ipc/job_main.py

When shutting down a job, I'd see:
```
2024-11-01 10:08:47,004 ERROR [livekit.agents] [log.py:21] [trace_id=1def6cfeeb92063a45eb46e9e9500303 span_id=d183818fae3b8fa7 resource.service.name= trace_sampled=True] - Error in _read_ipc_task                                                                                                                                                                                                                                                                                                    
Traceback (most recent call last):
File "/Users/martin/Library/Caches/pypoetry/virtualenvs/agent-x_OPPxuI-py3.12/lib/python3.12/site-packages/livekit/agents/utils/aio/duplex_unix.py", line 35, in recv_bytes
len_bytes = await self._reader.readexactly(4) …
```

Fix stack dump on shutdown

---

livekit-plugins/livekit-plugins-elevenlabs/livekit/plugins/elevenlabs/tts.py

While only supported for turbo v2.5, specifying language can be a helpful constraint. We currently overwrite your eleven labs tts to do this, upstreaming it here.

support language code in ElevenLabs TTS

---

.changeset/gentle-suits-cheat.md
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/api_proto.py
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model.py

Handles #1010  to include usage (number of input/output tokens) in the response_done event for realtime model
Conforms to the usage object model as shown at https://platform.openai.com/docs/api-reference/realtime-server-events/response/done at time of submission

Expose usage metrics for Realtime model

---

.changeset/warm-candles-kneel.md
livekit-agents/livekit/agents/pipeline/pipeline_agent.py
livekit-plugins/livekit-plugins-anthropic/livekit/plugins/anthropic/llm.py

fixes https://github.com/livekit/agents/issues/1048
docs: https://docs.anthropic.com/en/docs/build-with-claude/tool-use
encountered another issue while I was testing further for parallel tool calling, anthropic sends `RawMessageStopEvent` two times if there are two tool calls, ideally it should be just one time. @theomonnom @davidzhao 
```
2024-11-06 21:42:20,352 - DEBUG livekit.agents.pipeline - committed agent speech {"agent_transcript": " Hello from the weather station. Would you like to know the weather? If so, tell me your location.", "interrupted": false, "speech_id": "9c011146ed84"}
2024-11-06 21:42:25,055 - DEBUG livekit.agents.pipeline - received user transcript {"user_transcript": "London and Delhi."}
2024-11-06 21:42:26,158 - DEBUG livekit.agents.pipeline - validated agent …
```

anthropic tool issue

---

.changeset/tender-boxes-roll.md
livekit-agents/livekit/agents/metrics/base.py
livekit-agents/livekit/agents/vad.py

```py
@agent.on("metrics_collected")
def _on_metrics_collected(mtrcs: metrics.AgentMetrics):
if isinstance(mtrcs, metrics.PipelineVADMetrics):
logger.info(f"VAD metrics: idle_time={mtrcs.idle_time:.2f}")
metrics.log_metrics(mtrcs)
usage_collector.collect(mtrcs)
```
```
2024-11-10 07:00:08,775 - DEBUG livekit.agents.pipeline - speech playout finished {"speech_id": "5e2f1364bd6d", "interrupted": false}
2024-11-10 07:00:08,775 - DEBUG livekit.agents.pipeline - committed agent speech {"agent_transcript": " Hey, how can I help you today?", "interrupted": false, "speech_id": "5e2f1364bd6d"}
2024-11-10 07:00:09,195 - INFO voice-assistant - VAD metrics: idle_time=3.06 
2024-11-10 07:00:10,215 - INFO voice-assistant - VAD metrics: idle_time=4.08 
2024-11-10 07:00:11,234 - INFO voice-assistant - …
```

added idle time in vad metrics 

---

.changeset/breezy-rockets-camp.md
livekit-agents/livekit/agents/pipeline/pipeline_agent.py
livekit-agents/livekit/agents/pipeline/speech_handle.py

pipelineagent: fix speech_committed never called 

---

.changeset/empty-jars-shave.md
.github/workflows/tests.yml
examples/speech-to-text/transcriber.py
livekit-agents/livekit/agents/metrics/__init__.py
livekit-agents/livekit/agents/metrics/periodic_collector.py
livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/__init__.py
livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/stt.py

- energy filter should run on smaller chunks of audio
- it's disabled by default, as it's an optimization
- buffers audio frame immediately prior to energy detection to improve accuracy

fix Deepgram missing first word, disabled energy filter by default

---

.changeset/chatty-grapes-scream.md
livekit-plugins/livekit-plugins-google/livekit/plugins/google/models.py
livekit-plugins/livekit-plugins-google/livekit/plugins/google/stt.py
tests/pytest.ini
tests/test_stt.py

Add support for `chirp_2` [transcription model](https://cloud.google.com/speech-to-text/v2/docs/transcription-model), that is supported in both batch and streaming transcription see [release notes](https://cloud.google.com/speech-to-text/docs/release-notes#October_07_2024)
Update tests to include both default SST, and SST with new model passing specific [location and language](https://cloud.google.com/speech-to-text/v2/docs/speech-to-text-supported-languages).  Note that spoken punctuation is not supported with this model.

enh: Extending api to support chirp_2 model, and support passing location

---

.changeset/sharp-islands-flow.md
.changeset/tough-boats-appear.md
livekit-agents/livekit/agents/metrics/__init__.py
livekit-agents/livekit/agents/metrics/base.py
livekit-agents/livekit/agents/multimodal/multimodal_agent.py
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model.py

fix: expose multimodal agent metrics

---

.changeset/warm-suns-fly.md
livekit-plugins/livekit-plugins-playht/livekit/plugins/playht/models.py
livekit-plugins/livekit-plugins-playht/livekit/plugins/playht/tts.py

- Introduce "Play3.0-mini" to the TTSEngines literal for expanded voice engine options.
- Handle "wav" format in _encoding_from_format function for better output format support.
- Update default voice engine to "Play3.0-mini" for the DEFAULT_VOICE configuration.

feat(playht): add Play3.0-mini engine support

---

.changeset/gentle-dolphins-judge.md
examples/voice-pipeline-agent/function_calling_weather.py
livekit-agents/livekit/agents/pipeline/pipeline_agent.py

For https://github.com/livekit/agents/issues/1162
When adding the said message in function call to the end of the function call outputs, the LLM can complete the answer following the added text, for example
```python
agent.say("The current weather in New York is")
"overcast with a temperature of 37°F."
```
If the said message is added before the function call outputs, the LLM tend to repeat it some times
```python
The current weather in New York is  # agent.say
The current weather in New York is overcast with a temperature of 37°F.  # answer LLM output
```

fix: add extra_chat_message to the end of the function call outputs

---

.changeset/tough-chicken-obey.md
livekit-agents/livekit/agents/pipeline/pipeline_agent.py

Fix the duplicated `agent_speech_committed` events for the message with a function call.

fix: fix duplicated agent speech commit for message with function call

---

.changeset/twenty-apes-pay.md
tests/test_llm.py
tests/test_stt.py
tests/test_tts.py

This PR updates test names to enhance readability by adding id parameters in pytest.mark.parametrize.

Improve test names for better readability

---

tests/test_llm.py

Simplified prompts to help the LLM select the correct tool more reliably. Reduces ambiguity in tool selection scenarios.

Improve prompts to fix incorrect LLM tool calls during testing

---

.changeset/proud-starfishes-film.md
examples/voice-pipeline-agent/turn_detector.py
livekit-agents/livekit/agents/pipeline/pipeline_agent.py
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/llm.py
livekit-plugins/livekit-plugins-turn-detector/setup.py

it can take some time for final transcriptions to arrive. we would use end-of-speech timing to compute end of utterance delay, instead of from the moment final transcripts arrive.
also fixed the case where agents would be stuck when final transcripts do not end up coming in.
driveby, added a turn detector example

improvements to endpointing latency

---

.changeset/lazy-boats-drum.md
.changeset/wild-plants-dream.md
livekit-agents/livekit/agents/llm/function_context.py
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/_oai_api.py

This PR fixes ValueError when optional function args are set to `None`
Related issues: 
https://github.com/livekit/agents/issues/1185
https://github.com/livekit/agents/issues/1208

Handle optional func args in tool calls when set to `None`

---

livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/llm.py

OpenAI offers to store the conversations with metadata directly in their platform. This code enables that. There was an approved pull request for this but I closed it due to conflicts and errors in the main branch. Bringing it back now.
@davidzhao

Add store and metadata to LLMs

---

.github/workflows/build-package.yml
livekit-agents/livekit/agents/utils/images/image.py
livekit-plugins/livekit-plugins-anthropic/livekit/plugins/anthropic/llm.py
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/beta/assistant_llm.py
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/utils.py

Working on ChatImage, I noticed that center_aspect_fit gave the same result as center_aspect_cover for a portrait-oriented image (due to typo/bug in its logic). That's fixed, so now it letterboxes portrait images correctly.
I also noticed that our default implementation adds black letterboxing to images when they go to inference. This is undesirable, as the letterboxing may be misinterpreted as useful image data. It's better to send an image in its original aspect ratio and let the model's internal systems resize it in a way that allows it to ignore excess area (internally it will be seen as a square, but they may differ in what color/value they use for "blank pixels"). So I added a strategy called `scale_aspect_fit` and made it the new default.
I also added a method that lets you resize …

Fix center_aspect_fit, add center_aspect_scale resizing option

---

.changeset/fix-imgui-setup.md
livekit-plugins/livekit-plugins-browser/src/CMakeLists.txt

fix: fix `imgui` setup

---

.changeset/real-squids-warn.md
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/__init__.py
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model.py

Emit `session_updated` event from the `RealtimeSession` for anyone want to verify the session is correctly updated. Related to https://github.com/livekit/agents/issues/1183

fix: add session_updated event for realtime model

---

.changeset/clever-lies-explode.md
livekit-agents/livekit/agents/llm/__init__.py
livekit-agents/livekit/agents/llm/function_context.py
livekit-plugins/livekit-plugins-anthropic/livekit/plugins/anthropic/llm.py
livekit-plugins/livekit-plugins-assemblyai/livekit/plugins/assemblyai/stt.py
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/_oai_api.py
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/llm.py
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model.py

- Moved `create_ai_function_info` to function_context.py for better reusability and reduce repetation
- Fixes `UnboundLocalError` in `test_stt.py::test_stream[24000-assemblyai]` by ensuring `ws` is initialized before access.

Move `create_ai_function_info` to function_context.py

---

.changeset/pre.json
.github/workflows/build-package.yml
.github/workflows/publish-package.yml
livekit-plugins/livekit-plugins-anthropic/setup.py
livekit-plugins/livekit-plugins-assemblyai/setup.py
livekit-plugins/livekit-plugins-azure/setup.py
livekit-plugins/livekit-plugins-browser/setup.py
livekit-plugins/livekit-plugins-cartesia/setup.py
livekit-plugins/livekit-plugins-clova/setup.py
livekit-plugins/livekit-plugins-deepgram/setup.py
livekit-plugins/livekit-plugins-elevenlabs/setup.py
livekit-plugins/livekit-plugins-fal/setup.py
livekit-plugins/livekit-plugins-google/setup.py
livekit-plugins/livekit-plugins-llama-index/setup.py
livekit-plugins/livekit-plugins-openai/setup.py
livekit-plugins/livekit-plugins-playht/setup.py
livekit-plugins/livekit-plugins-rag/setup.py
livekit-plugins/livekit-plugins-silero/setup.py
livekit-plugins/livekit-plugins-turn-detector/setup.py

upload-artifacts v4 has [a breaking change](https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes) that impacts our CI.
We rely on uploading to the same directory for build + publish, they no longer support it.
reverting for now so we can get some builds out

Revert to upload-artifacts@v3, update dependency versions

---

.github/workflows/build-package.yml
.github/workflows/publish-package.yml

Sorry about the previous breaking PR, this shouldn't have slipped past, but I only relied on the CI passing in the PR. 
While it's not possible to upload multiple artifacts to the same name anymore with the v4 upload artifact action, it _is_ possible to merge multiple artifact downloads into the same folder with v4 download artifact.
This PR merges all artifacts with the pattern `python-package-dist-*` into the `dist` folder. The idea is that no other changes are required, keeping the diff here minimal. Don't have a good way to test this though.

Update to v4 versions with multiple artifact download

---

.changeset/curvy-knives-promise.md
examples/voice-pipeline-agent/function_calling_weather.py
livekit-agents/livekit/agents/pipeline/pipeline_agent.py
livekit-agents/livekit/agents/pipeline/speech_handle.py

When there is a message along with the function calls, the message will be added to the chat ctx twice: after it's played, and after the function calls finished.
```python
[
...
ChatMessage(role='assistant',
id='item_1158d15105e5',
name=None,
content=' Hello from the weather station. Would you like to know '
'the weather? If so, tell me your location.',
tool_calls=None,
tool_call_id=None,
tool_exception=None),
ChatMessage(role='user',
id='item_bf51c7ec1c80',
name=None,
content='New York.',
tool_calls=None,
tool_call_id=None,
tool_exception=None),
ChatMessage(role='assistant',
id='item_d41fa35f7251',
name=None,
content=' Let me check the weather in New York for you.',
tool_calls=None,
tool_call_id=None,
tool_exception=None),
ChatMessage(role='assistant',
id='item_cb041bd44d6c',
name=None, …
```

fix: avoid duplicated chat ctx for function call with messages

---

.changeset/lazy-dragons-give.md
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/llm.py

adding metadata & store break Groq & Cerebras API

fix unknown `metadata` & `store` fields on OpenAI-like API

---

.changeset/nasty-rings-wave.md
examples/voice-pipeline-agent/function_calling_weather.py
livekit-agents/livekit/agents/llm/function_context.py
tests/test_create_func.py

`@llm.ai_callable` need a explicit `description=llm.USE_DOCSTRING` to use the docstring as the description.

fix: set USE_DOCSTRING as default for ai_callable

---

livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/llm.py

Google Cloud offers other authentication methods apart from the env variable: see [here](https://cloud.google.com/docs/authentication/application-default-credentials)
Thus, if this variable is not set, we should show a warning, but not raise an error, as the user might be using other methods

Substitute google error for warning

---

.changeset/witty-fishes-stare.md
livekit-agents/livekit/agents/pipeline/pipeline_agent.py

If a function has been called but the extra tools haven't been committed to the chat context, the response will be generated with a copied chat ctx that doesn't include those calls, and thus the LLM will 're-call' them.
This is a fix so the copied chat ctx contains those calls as well.

fix context when functions have been called

---

.changeset/silent-oranges-warn.md
livekit-agents/livekit/agents/pipeline/pipeline_agent.py

there are a couple of conditions that could cause the agent to be stuck. This is because the current speech could be interrupted first (because it's acting on VAD events), but the handling of that event only comes in later during validations. 
this change ensures that if we ever get to the validation stage, and the agent is not currently speaking, we would always generate a new thread, even if the incoming transcript is empty. If interrupted with a cough (as an example), it will allow the agent to pick up from where it'd left off.
fixes #1229

improve interruption handling, avoid agent from getting stuck

---

.changeset/hot-trainers-press.md
livekit-plugins/livekit-plugins-assemblyai/livekit/plugins/assemblyai/stt.py

Boost words do not work with the Assembly AI plugin as they are not encoded in the URL. This fix encodes them.

encode boost words

---

.changeset/giant-ways-invite.md
livekit-agents/livekit/agents/_exceptions.py
livekit-plugins/livekit-plugins-assemblyai/livekit/plugins/assemblyai/stt.py
livekit-plugins/livekit-plugins-azure/livekit/plugins/azure/stt.py
livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/stt.py
livekit-plugins/livekit-plugins-google/livekit/plugins/google/stt.py

when #1131 changed plugins to use `asyncio.await` instead of `asyncio.gather`, it broke the retry mechanisms that we had.
`.gather` automatically propagates exceptions, while `.await` does not. this means we'd have to propagate them explicitly in order for retries to work.

Ensure STT exceptions are being propagated

---

.changeset/gorgeous-sheep-grow.md
livekit-agents/livekit/agents/_exceptions.py
livekit-agents/livekit/agents/llm/llm.py
livekit-plugins/livekit-plugins-anthropic/livekit/plugins/anthropic/llm.py
livekit-plugins/livekit-plugins-cartesia/livekit/plugins/cartesia/tts.py
livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/tts.py
livekit-plugins/livekit-plugins-elevenlabs/livekit/plugins/elevenlabs/tts.py
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/llm.py

LLM could timeout after producing initial tokens, in those cases the inference request should not be retried. the error would be propagated to the caller (PipelineAgent), who could handle it similarly to an interruption. (i.e. flagging it and performing new inference)

improved handling of LLM errors, do not retry if already began

---

.changeset/khaki-candles-rest.md
livekit-agents/livekit/agents/pipeline/pipeline_agent.py

As it stands, the agent just stops when it hits the maximum depth - this way it'll be forced to synthesize a reply.

Do not pass function context if at max depth

---

examples/voice-pipeline-agent/function_calling_weather.py

In function calling weather example, skip the `say` if there is already a message alongside the function call.

avoid duplicate say in function call example

---

.changeset/quiet-dots-fly.md
examples/voice-pipeline-agent/function_calling_weather.py
livekit-agents/livekit/agents/pipeline/pipeline_agent.py

currently we'd get warnings when synthesizing the response to a function call. due to a current limitation, we aren't able to only include the function that we are processing.

avoid warnings when function depth matches limit

---

.changeset/lazy-buckets-obey.md
livekit-agents/livekit/agents/ipc/job_proc_executor.py

we were marking every job as failed to the server, due to an order of op error. _main_task is running within the subprocess, and would not be able to retrieve its own exit code.
it was always None, and was evaluated to JobStatus.FAILED

ensure job status updates contain the correct status

---

.changeset/dry-drinks-poke.md
livekit-agents/livekit/agents/transcription/tts_forwarder.py

Really just wrapping in a try block!
This would cause errors like:
```
{"message": "Task was destroyed but it is pending!\ntask: <Task pending name='Task-124' coro=<TTSSegmentsForwarder._main_task.<locals>._forward_task() running at /app/.venv/lib/python3.12/site-packages/livekit/agents/utils/log.py:16> wait_for=<Future pending cb=[Task.task_wakeup()]>>", "level": "ERROR", "name": "asyncio", "pid": 1923, "job_id": "AJ_VKu3CSTZGMS9", "timestamp": "2025-01-06T18:11:34.516550+00:00"}
```
Fixes: #1264

Fix not awaiting forward task

---

.changeset/funny-buttons-taste.md
.changeset/wild-planes-cheer.md
livekit-agents/livekit/agents/llm/llm.py
livekit-agents/livekit/agents/stt/stt.py
livekit-agents/livekit/agents/tts/tts.py
livekit-agents/livekit/agents/types.py
livekit-plugins/livekit-plugins-azure/livekit/plugins/azure/stt.py
livekit-plugins/livekit-plugins-google/livekit/plugins/google/stt.py

also reduces initial retry delay with STT/LLM/TTS connection errors
fixes #1258

fix Google STT handling of session timeouts

---

.changeset/cool-clouds-hang.md
livekit-plugins/livekit-plugins-cartesia/livekit/plugins/cartesia/models.py
livekit-plugins/livekit-plugins-cartesia/livekit/plugins/cartesia/tts.py

This change updates the default model to `sonic` (see https://docs.cartesia.ai/build-with-sonic/models for details about our model aliases).
It also updates the default voice ID to one that we like a bit better.
(Hope you all are doing well :)

update Cartesia plugin default model and voice id

---

.changeset/hip-bottles-joke.md
livekit-agents/livekit/agents/pipeline/pipeline_agent.py

Someone in Slack has encountered this bug, where function calls without a text response are not added to the chat ctx, e.g. the first fnc in a nested function call returns another fnc but no text.
Fixed this by moving the collected text check to after adding the function call in the chat ctx.

fix: function calls without text response are not added to chat ctx

---

.changeset/twenty-rockets-approve.md
livekit-agents/livekit/agents/multimodal/multimodal_agent.py
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model.py

To disable the server VAD for OAI realtime api, set `turn_detection=None`
```python
model=openai.realtime.RealtimeModel(
voice="alloy",
temperature=0.8,
instructions="You are a helpful assistant",
turn_detection=None,
)
```
To manually commit user speech and trigger response:
```python
session: RealtimeSession = agent._session
session.input_audio_buffer.commit() 
@agent.on("input_speech_committed")
def _on_input_speech_committed():
agent.interrupt()  # can also be called when the local VAD detects the start of the user speech
session: RealtimeSession = agent._session
session.response.create(on_duplicate="cancel_existing")
```

Support manual vad for realtime api

---

README.md

Updates the Readme to use the correct spelling for [x.ai's Grok](https://x.ai/grok) not to be confused with [Groq](https://groq.com/) which has a separate plugin for LLM inference.

chore(README Typo): x.ai grok not groq

---

.changeset/blue-boats-sin.md
livekit-plugins/livekit-plugins-azure/livekit/plugins/azure/stt.py
livekit-plugins/livekit-plugins-azure/livekit/plugins/azure/tts.py

Pass all options to the `SpeechConfig` as it already has the sanity check (https://learn.microsoft.com/en-us/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech.speechconfig?view=azure-python)
```python
if endpoint is not None or host is not None:
if region is not None:
raise ValueError('cannot construct SpeechConfig with both region and endpoint or host information')
if auth_token is not None:
raise ValueError('cannot specify both auth_token and endpoint or host when constructing SpeechConfig. '
'Set authorization token separately after creating SpeechConfig.')
if region is not None and subscription is None and auth_token is None:
raise ValueError('either subscription key or authorization token must be given along with a region')
if subscription is not None and …
```

fix azure speech for all types of configs

---

.changeset/young-monkeys-allow.md
livekit-agents/setup.py

This is causing very long connection time for some users
Using this library should be an user choice, not a choice made by livekit-agents

remove aiodns from livekit-agents

---

tests/test_llm.py

- The Vertex LLM frequently fails due to rate limits, so we are temporarily disabling it.

disable vertex from test_llm.py

---

livekit-agents/livekit/agents/pipeline/pipeline_agent.py

This is the same fix as for the main chat context when speech is committed but to make sure that when we call the LLM with a copied chat_ctx, just after a tool call, we don't have the tool text message duplicated
@longcw

remove duplicated message

---

examples/text-to-speech/cartesia_tts.py

according to Cartesia, their /bytes endpoint doesn't support continuations. streaming endpoint produces a more natural speech.

update Cartesia example to use streaming

---

livekit-plugins/livekit-plugins-azure/livekit/plugins/azure/tts.py

added possibility to add styles to voices (see [documentation](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/speech-synthesis-markup-voice#style-and-degree-example))

Plugin azure add voice styles

---

livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/api_proto.py
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model.py

I recently came across new additions that OpenAI developed and would love for them to be included in Livekit!
I worked on [out-of-band responses](https://platform.openai.com/docs/guides/realtime-model-capabilities#create-responses-outside-the-default-conversation) and an [extra VAD option](https://platform.openai.com/docs/guides/realtime-model-capabilities#voice-activity-detection-vad) where responses are not automatic. I also added an option to turn server VAD off by `turn_detection="None"`  in `session.update()`.
Please let me know your thoughts! :-)

Add out-of-band responses + controlled response timing 

---

.changeset/modern-seas-push.md
examples/voice-pipeline-agent/fallback_adapter.py
livekit-agents/livekit/agents/llm/fallback_adapter.py

fix: ensure llm.FallbackAdapter executes function calls correctly

---

.changeset/famous-owls-attack.md
livekit-agents/livekit/agents/pipeline/pipeline_agent.py

LLMs like Anthropic and Gemini do not accept empty content as part of the user question. Using a continue marker to ensure output continues from point of interruption

fix false positive interruption tripping up certain LLMs

---

.changeset/rich-spiders-develop.md
livekit-plugins/livekit-plugins-google/livekit/plugins/google/llm.py

According to the Google Auth library, authentication should be possible without the `GOOGLE_APPLICATION_CREDENTIALS` environment variable by using commands like `gcloud auth application-default login` and `gcloud config set project` . However, the current implementation does not support this, so this pull request addresses and fixes that issue by logging a warning instead of raising a `ValueError` when the environment variable is not set. This change ensures consistency with the existing implementation and allows the use of alternative Google authentication methods.
* Replace the `ValueError` with a `logger.warning`
By modifying the implementation to log a warning instead of raising an error, this pull request aligns the behavior with the intended flexibility of the Google Auth library …

chore: Replace ValueError with logger.warning for missing GOOGLE_APPLICATION_CREDENTIALS environment variable

---

.changeset/slimy-houses-sin.md
livekit-agents/livekit/agents/llm/fallback_adapter.py

when an LLM is in a failing state, sometimes that failure isn't discovered right away, but only when we attempt to iterate through the chunks. #1409 executes function correctly only when failure mode was not encountered

fix: fallbackadapter to correctly handle function calls

---

.changeset/little-phones-drive.md
livekit-plugins/install_plugins_editable.sh
livekit-plugins/livekit-plugins-google/livekit/plugins/google/stt.py

* Additional update to support setting `client_options` for other SpeechAsyncClient constructors
- extends #1089 
* Update tests install for FAL
cc @theomonnom

enh: Update to also pass ClientOptions to credentials args

---

.github/workflows/publish-package.yml

Current SHA is a few years old - https://github.com/pypa/gh-action-pypi-publish/releases/tag/v1.4.2 - proposing updating to the latest https://github.com/pypa/gh-action-pypi-publish/releases/tag/v1.12.4

Bump version of pypa/gh-action-pypi-publish in workflows/publish-package.yml

---

.changeset/kind-parrots-help.md
examples/voice-pipeline-agent/function_calling_weather.py
livekit-plugins/livekit-plugins-google/livekit/plugins/google/beta/realtime/api_proto.py
livekit-plugins/livekit-plugins-google/livekit/plugins/google/beta/realtime/realtime_api.py
livekit-plugins/livekit-plugins-google/livekit/plugins/google/beta/realtime/transcriber.py
livekit-plugins/livekit-plugins-google/livekit/plugins/google/llm.py
livekit-plugins/livekit-plugins-google/livekit/plugins/google/models.py
tests/test_llm.py

- add latest models from google
- updated testcase for array arguments

Gemini Realtime: Transcribe model audio via gemini api 

---

livekit-plugins/livekit-plugins-cartesia/livekit/plugins/cartesia/tts.py

Per request from some of our customers, we want to provide the optionality to specify the base URL for the Cartesia API when using the Cartesia TTS plugin, including localhost for debugging purposes.

[Cartesia] Adding base url option to Cartesia TTS plugin

---

.changeset/nine-foxes-wink.md
livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/models.py

With the early access release of [Nova 3 from Deepgram](https://developers.deepgram.com/docs/models-languages-overview#nova-3) add the general model to the model type literal for STT

chore(Deepgram STT): add nova-3 model to type literal

---

.changeset/late-dolphins-help.md
livekit-plugins/livekit-plugins-turn-detector/livekit/plugins/turn_detector/eou.py

this should fix the utterance delays at _true turn endings_ that some folks have noticed with the new model. 
with this updated threshold the new model has the same TPR (true positive rate) as the old model,  but a much higher TNR. in other words, it's better at preventing interruptions from the agent, without sacrificing higher latency at true turn endings.
for reference, here's the metrics comparison using our latest evaluation set:
```
threshold    tpr    tnr
OLD model OLD threshold      0.150  0.988  0.796
NEW model OLD threshold      0.150  0.943  0.976
NEW model NEW threshold      0.008  0.988  0.905
```

Fix prob cutoff

---

livekit-agents/livekit/agents/pipeline/pipeline_agent.py

If the EOU predictor is not responsive and returns non the assertion error should not cause the PipelineAgent to die.

End of utterance Assertion Error Rescue

---

.changeset/warm-seahorses-hunt.md
livekit-agents/livekit/agents/pipeline/pipeline_agent.py

This pr supports calling `agent.say` inside a `before_llm_cb`, it will playout the content of say first then the returned llm stream
```python
async def before_llm_cb(
agent: VoicePipelineAgent, chat_ctx: llm.ChatContext
) -> llm.LLMStream:
speech_handle = await agent.say("say something")
llm_stream = agent.llm.chat(chat_ctx=chat_ctx, fnc_ctx=agent.fnc_ctx)
return llm_stream
```

support agent.say in before_llm_cb

---

.changeset/proud-onions-drop.md
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/api_proto.py
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model.py

Fixed a bug since https://github.com/livekit/agents/pull/1320 that overwrites the instructions with empty unexpectedly during response creation in the OpenAI Realtime model.

fix openai realtime response create

---

.changeset/rare-trains-bake.md
livekit-plugins/livekit-plugins-google/livekit/plugins/google/beta/realtime/realtime_api.py

- gemini realtime is still experimental

Gemini realtime : rollback default model to `gemini-2.0-flash-exp`

---

livekit-plugins/livekit-plugins-assemblyai/livekit/plugins/assemblyai/stt.py

`_process_stream_event` implicitly assumed that error messages from AssemblyAI had a `message_type` key. The [docs](https://www.assemblyai.com/docs/speech-to-text/streaming) show that this is not the case, and error messages have only the `error` key. This changes reflects this fact and refactors a bit for clarity + robustness.

AssemblyAI plugin bugfix

---

.changeset/sixty-plums-teach.md
livekit-agents/livekit/agents/pipeline/pipeline_agent.py

Fix RuntimeError when the main speech was interrupted but continued `synthesis_handle.play()` if the interruption occurred at the end of a nested speech from `before_llm_cb`. https://github.com/livekit/agents/issues/1503

fix interrupting nested speech from before_llm_cb

---

livekit-agents/livekit/agents/cli/cli.py

Use `os.getcwd()` to set the `main_file` path, ensuring it points to the current working directory instead of the script directory. This change solves problems on script execution context handling in managed virtual enviroments such as rye/uv/poetry.
edit: This causes problem when `--watch` enabled. It's looking for changes on `.venv/bin` dir.

fix(cli): update main_file path to use current directory

---

.changeset/heavy-moose-juggle.md
livekit-plugins/livekit-plugins-turn-detector/livekit/plugins/turn_detector/eou.py

this will preserve any logging context that we are adding

chore(turn-detector): log from job process instead of inference

---

.changeset/weak-weeks-shave.md
livekit-plugins/livekit-plugins-azure/livekit/plugins/azure/tts.py

Adding handlers for each of the `SpeechSynthesizer` subscribable events according to the [docs](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/how-to-speech-synthesis?tabs=browserjs%2Cterminal&pivots=programming-language-python):
- `BookmarkReached`
- `SynthesisCanceled`
- `SynthesisCompleted`
- `SynthesisStarted`
- `Synthesizing`
- `VisemeReceived`
- `WordBoundary`

Add handlers for supported synthesis events for Azure TTS

---

.github/workflows/tests.yml

GitHub includes usage of the following runners for free for public repos:
https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

test gha uses github standard arm runner

---

.github/workflows/tests.yml

updating images ahead of deprecation. updating all images, not just ubuntu-20.04.
https://github.com/actions/runner-images/issues/11101

update test runner images

---

.changeset/eighty-bikes-speak.md
examples/avatar/agent_worker.py
examples/ds_chat_test.py
examples/minimal_worker.py
examples/roomio_worker.py
livekit-agents/livekit/agents/pipeline/io.py
livekit-agents/livekit/agents/pipeline/room_io.py
livekit-agents/livekit/agents/pipeline/transcription/synchronizer.py
livekit-agents/setup.py

depends on https://github.com/livekit/python-sdks/pull/362

Add text stream sink and multi text sink

---

.changeset/weak-rabbits-cheat.md
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/llm.py

This pull request introduces a new `max_tokens` parameter to the `LLMOptions` and related methods in the `livekit-plugins/livekit-plugins-openai` package. The changes ensure that the `max_tokens` parameter is properly integrated and utilized within the class methods.
Key changes include:
* Added `max_tokens` parameter to `LLMOptions` class in `livekit/plugins/openai/llm.py`.
* Updated `__init__` method to accept and initialize `max_tokens` parameter in `livekit/plugins/openai/llm.py`. [[1]](diffhunk://#diff-0186148b58ae1916b3785d774437ad73ec257f2cf4a83d6adb686413aa041febR86) [[2]](diffhunk://#diff-0186148b58ae1916b3785d774437ad73ec257f2cf4a83d6adb686413aa041febR109)
* Modified `with_groq` method to include `max_tokens` parameter in `livekit/plugins/openai/llm.py`. …

feat: add max_tokens option to LLM and LLMStream classes

---

livekit-plugins/livekit-plugins-google/livekit/plugins/google/_utils.py
livekit-plugins/livekit-plugins-google/livekit/plugins/google/beta/realtime/realtime_api.py
livekit-plugins/livekit-plugins-google/livekit/plugins/google/beta/realtime/transcriber.py
livekit-plugins/livekit-plugins-google/livekit/plugins/google/llm.py
livekit-plugins/livekit-plugins-google/setup.py

- update `google-genai` version to latest `1.1.0`
- roll back default model to `gemini-2.0-flash-exp` for realtime, fixes https://github.com/livekit/agents/issues/1466

google-genai version bump

---

.changeset/popular-dragons-arrive.md
livekit-agents/livekit/agents/ipc/job_proc_lazy_main.py
livekit-agents/livekit/agents/ipc/proc_client.py
livekit-agents/livekit/agents/ipc/proc_pool.py
livekit-agents/livekit/agents/ipc/proto.py
livekit-agents/livekit/agents/ipc/supervised_proc.py
livekit-agents/livekit/agents/worker.py

catch user initialization cb failures & allow concurrent proc initializations

handle process initialization failure 

---

.changeset/brave-brooms-rest.md
.changeset/soft-tips-care.md
livekit-plugins/install_plugins_editable.sh
livekit-plugins/livekit-plugins-anthropic/livekit/plugins/anthropic/llm.py
livekit-plugins/livekit-plugins-aws/livekit/plugins/aws/_utils.py
livekit-plugins/livekit-plugins-aws/livekit/plugins/aws/llm.py
livekit-plugins/livekit-plugins-google/livekit/plugins/google/_utils.py
livekit-plugins/livekit-plugins-google/livekit/plugins/google/models.py
livekit-plugins/livekit-plugins-google/livekit/plugins/google/stt.py
tests/test_llm.py
tests/test_stt.py

- added test case for consecutive messages in chat context

change default model for google stt and add aws llm test case

---

.changeset/mighty-pandas-dress.md
.changeset/tender-beds-chew.md
livekit-plugins/livekit-plugins-elevenlabs/livekit/plugins/elevenlabs/tts.py

Elevenlabs added a speed parameter in the last release: https://elevenlabs.io/docs/changelog/2025/2/25#text-to-speech

Add elevenlabs speed parameter

---

examples/Dockerfile-example

This PR updates `examples/Dockerfile-example` to include `g++` as a build dependency, fixing a build failure when using the `requirements.txt` from `examples/voice-pipeline-agent/`. The `annoy` package, a transitive dependency of one of the listed packages (likely `livekit-plugins-silero`), requires a C++ compiler, but the original Dockerfile only included `gcc`.
When building the Docker image with:
- Dockerfile: `examples/Dockerfile-example`
- `requirements.txt`: `examples/voice-pipeline-agent/requirements.txt`
The process fails with:
```
gcc: fatal error: cannot execute ‘cc1plus’: execvp: No such file or directory
compilation terminated.
error: command '/usr/bin/gcc' failed with exit code 1
ERROR: Failed building wheel for annoy
```
This happens because `annoy` contains C++ code (e.g., …

Added g++ to Dockerfile-example to Support Building annoy Dependency

---

.changeset/pink-kiwis-grab.md
livekit-agents/livekit/agents/pipeline/pipeline_agent.py

When a new _synthesize_answer_task is created, it is possible that the old _synthesize_answer_task is waiting for the llm_stream at
```python
llm_stream = await llm_stream
```
In this case, the new task will cancel the old one. However, the handle of the old task is not correctly canceled.
This would result in the handle never being initialized by `_synthesize_answer_task`.
As a result, the `_play_speech` function will stuck at `await speech_handle.wait_for_initialization()`, and blocks all the subsequent speeches.
Note that the old handle is supposed to be canceled by `self._pending_agent_reply.cancel()` in the `_synthesize_agent_reply function`. However, this is not working properly since `self._pending_agent_reply` is assigned to `None` in the `_validate_reply_if_possible` function.

Bug fix: _play_speech get stuck due to orphan speech handle.

---

.changeset/lemon-eagles-glow.md
livekit-plugins/livekit-plugins-azure/livekit/plugins/azure/stt.py

The Azure SDK’s default setting of `ProfanityOption.Masked` can cause issues with certain sentences.

feat: Azure.STT support profanity_option

---

examples/hive-moderation-agent/requirements.txt
examples/participant-entrypoint/requirements.txt
examples/simple-color/requirements.txt
examples/speech-to-text/requirements.txt
examples/text-to-speech/requirements.txt
examples/voice-pipeline-agent/requirements.txt

Updating the package requirements for pre-1.0 examples to ensure that we only pull versions prior to v1.0.0 in order to maintain compatibility.

Restrict v0 examples package requirements to <1.0

---

.changeset/blue-ants-heal.md
.changeset/eleven-brooms-watch.md
.changeset/fluffy-apricots-attack.md
examples/voice-pipeline-agent/function_calling_weather.py
livekit-agents/livekit/agents/cli/log.py
livekit-agents/livekit/agents/pipeline/agent_output.py
livekit-agents/livekit/agents/tts/fallback_adapter.py
livekit-agents/livekit/agents/tts/stream_adapter.py
livekit-agents/livekit/agents/tts/tts.py
livekit-agents/livekit/agents/utils/codecs/decoder.py
livekit-agents/livekit/agents/utils/connection_pool.py
livekit-plugins/livekit-plugins-aws/livekit/plugins/aws/log.py
livekit-plugins/livekit-plugins-cartesia/livekit/plugins/cartesia/tts.py
livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/stt.py
livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/tts.py
livekit-plugins/livekit-plugins-elevenlabs/livekit/plugins/elevenlabs/tts.py
livekit-plugins/livekit-plugins-google/livekit/plugins/google/stt.py
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/tts.py
livekit-plugins/livekit-plugins-speechmatics/livekit/plugins/speechmatics/stt.py
tests/test_stt.py

- added a tts.prewarm method to start the connection pool early. we should do this automatically in v1. currently just the stubs
- in agent_output, combined both streaming and non-streaming synthesis paths
- fixed a bug in AudioStreamDecoder where it could fail on close
- deprecated elevenlabs' `optimize_stream_latency` option

handle decoder errors and tts prewarm

---

livekit-plugins/livekit-plugins-openai/setup.py

since this is a dev version it won't automatically meet the `>=0.12.3` criteria and in docker build it gets stuck in an unfulfillable dependency hell. not sure why it doesn't in venv though.

bump openai plugin agents dependency version

---

livekit-plugins/livekit-plugins-cartesia/livekit/plugins/cartesia/models.py
livekit-plugins/livekit-plugins-cartesia/livekit/plugins/cartesia/tts.py

Two changes:
- Updating the model literals for the Cartesia TTS Integration
- Changing the model default from `sonic` to `sonic-2`, our latest model release

[Cartesia] Adding new model literals, updating default to sonic-2

---

.changeset/fresh-foxes-remember.md
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/api_proto.py
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model.py
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/stt.py

As per the [documentation](https://platform.openai.com/docs/api-reference/realtime-sessions/create#realtime-sessions-create-input_audio_transcription), the OpenAI realtime API allows to specify `language` and `prompt` parameters as input to the transcription model. This PR adds support for it.
Closes #1430.

Support more input transcription parameters for openai realtime

---

.changeset/1682.md
livekit-agents/setup.py

These are behind latest
See also https://iscinumpy.dev/post/bound-version-constraints/

Remove unnecessary version pins

---

.changeset/healthy-seahorses-sneeze.md
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/llm.py

and default azure to the same as openai, instead of the default 10 mins

Make azure and openai take a timeout optionally

---

.changeset/dirty-countries-rescue.md
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/stt.py

Current implementation only allows for using `server_vad`, but many use cases would benefit from the addition of `semantic_vad` support

feat(OpenAI STT): add support for semantic_vad

---

livekit-plugins/livekit-plugins-aws/livekit/plugins/aws/llm.py

This PR adds token usage tracking for AWS Bedrock LLM models. Previously, when using AWS Bedrock models, the token counts (`llm_prompt_tokens` and `llm_completion_tokens`) were always zero, resulting in incorrect cost calculations. The implementation now correctly extracts token usage data from the AWS Bedrock API response metadata.
When running agents with AWS Bedrock LLM models, the `UsageCollector` returns zero values for `summary.llm_prompt_tokens` and `summary.llm_completion_tokens`, making cost calculations incorrect when using code like:
```python
lm_cost = (
summary.llm_prompt_tokens * BEDROCK_LLM_INPUT_PRICE
+ summary.llm_completion_tokens * BEDROCK_LLM_OUTPUT_PRICE
)
```
Updated the AWS plugin to extract token usage information from the metadata section of the AWS Bedrock …

feat: add usage tracking to AWS LLM plugin

---

.github/next-release/changeset-b63aa935.md
livekit-agents/livekit/agents/voice/agent_activity.py

Fix those errors:
```
2025-03-27 14:02:54,262 - ERROR asyncio - Task exception was never retrieved
future: <Task finished name='Task-29' coro=<<async_generator_athrow without __name__>()> exception=RuntimeError('aclose(): asynchronous generator is already running')> 
RuntimeError: aclose(): asynchronous generator is already running
2025-03-27 14:02:54,267 - ERROR asyncio - Task was destroyed but it is pending!
task: <Task pending name='Task-17' coro=<_text_forwarding_task() done, defined at /Users/theomonnom/livekit/agents/livekit-agents/livekit/agents/utils/log.py:13> wait_for=<Future pending cb=[Task.task_wakeup()]>> 
2025-03-27 14:02:54,267 - ERROR asyncio - Task was destroyed but it is pending!
task: <Task pending name='Task-18' coro=<_audio_forwarding_task() done, defined at …
```

fix leaked tasks on realtime generation

---

.github/next-release/changeset-23110904.md
livekit-agents/livekit/agents/llm/chat_context.py
livekit-agents/livekit/agents/voice/generation.py

`update_instructions` on copied chat ctx still modifies the original `chat_ctx` bc the it's a shadow copy.

fix update_instructions on copied chat ctx

---

.github/next-release/changeset-ed61ef0b.md
livekit-agents/livekit/agents/cli/cli.py

LiveKit keys should be optional for the console subcommand

use fake keys for the console subcommand

---

livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/__init__.py
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/api_proto.py
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model.py

There is a new VAD mechanism available to the OpenAI realtime model: semantic VAD.
https://platform.openai.com/docs/guides/realtime-vad#semantic-vad
I've added this option to the OpenAI realtime plugin.

Added a Semantic VAD configuration option

---

.github/next-release/changeset-814000cb.md
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model.py

https://livekit-users.slack.com/archives/C07FY8WHGPM/p1743479917168779
> In v1rc4, I have this weird issue where ChatGPT realtime will do the initial generate_reply() with the default voice, then switch to selected voice for next replies.
```python
session = AgentSession(
llm=openai.realtime.RealtimeModel(
model="gpt-4o-realtime-preview",
voice='ash'
),
vad=ctx.proc.userdata["vad"],
)
await session.start(
room=ctx.room,
agent=assistant,
room_input_options=room_io.RoomInputOptions(
),
room_output_options=room_io.RoomOutputOptions(
transcription_enabled=True
)
)
await session.generate_reply()
```

fix initial session update for realtime model

---

.github/next-release/changeset-eaa2b51d.md
examples/voice_agents/extending-logger.py
livekit-agents/livekit/agents/__init__.py
livekit-agents/livekit/agents/ipc/job_proc_lazy_main.py
livekit-agents/livekit/agents/job.py
livekit-agents/livekit/agents/voice/__init__.py

This add a way to inject fields to every log (and is JobContext aware — also works for THREAD executor type).
Exposing the logger is going to be too hard for now, we have a quite opinionated approach with IPC 
handles https://github.com/livekit/agents/issues/1815 
will add the worker_id in another PR

add log_context_fields

---

livekit-plugins/livekit-plugins-speechmatics/livekit/plugins/speechmatics/types.py

- Added two new options from their latest doc;
- Removed one that does not exist in the doc and caused issues in my testing.
Hi @dumitrugutu, just want to double-check with you on the `streaming_mode` flag. I couldn't find it in the latest [docs](https://docs.speechmatics.com/rt-api-ref#transcription-config), and whenever I enabled it, the plugin did not work. Do you have any ideas about this parameter/issue?
The issue message whenever streaming_mode is set to True:
```text
{"message": "failed to recognize speech, retrying in 0.1s\nTraceback (most recent call last):\n  File \"/Users/chenghao/Developer/ai-worker/.venv/lib/python3.12/site-packages/livekit/agents/stt/stt.py\", line 218, in _main_task\n    return await self._run()\n           ^^^^^^^^^^^^^^^^^\n  File …
```

added new parameters and removed unused one in Speechmatics

---

.github/next-release/changeset-5f2df41d.md
livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/stt.py

This address the second issue mentioned in #1887 
Reference docs: 
- https://developers.deepgram.com/docs/keywords
- https://developers.deepgram.com/docs/keyterm
TL;DR
keyterms only work with Nova-3 in English;
keywords work with other models;

Add Deepgram keyterms validataion

---

.github/next-release/changeset-65b3292c.md
livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/stt.py

Nova-3 already supports multi-language, as you can see here: https://deepgram.com/learn/introducing-nova-3-speech-to-text-api
> Nova-3 is the first voice AI model to offer real-time multilingual transcription.
But, if you tried with a configuration like this one:
```python
deepgram_stt = deepgram.STT(
model='nova-3',
language='multi',
)
```
You will receive this error in the logs and it will switch back to `nova-2`:
So remove the `nova-3` model from the English-only Deepgram models.

Deepgram Nova-3 multi-language support

---

examples/voice_agents/llamaindex-rag/retrieval.py
examples/voice_agents/speedup_output_audio.py
examples/voice_agents/structured_output.py
livekit-agents/livekit/agents/voice/agent.py

The implementation is separated now into Agent.default now (inner class) 
We should recommend people to use `Agent.default.tts_node` instead of `super().tts_node`.
The only difference is the type checker being confused by the latter but both are compatible at runtime. 
The reason why type checkers are confused is because llm_node/tts_node/... could either be an AsyncGenerator or a Coroutine.

fix nodes types

---

examples/voice_agents/push_to_talk.py
livekit-agents/livekit/agents/voice/agent.py
livekit-agents/livekit/agents/voice/agent_activity.py
livekit-agents/livekit/agents/voice/agent_session.py

- This is currently only implemented for the stateless LLM, this will require more work for the Realtime models (We will need to hash each message, and find the differences to update to the OpenAI server)
- The changes made to the chat_ctx are only for the current turn, they're not preserved inside the Agent.chat_ctx (Only the new user message will be kept)

allow to edit the chat_ctx inside on_user_turn_completed

---

livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/stt.py

Previously, when a call ends, we got `raise APIStatusError(message="deepgram connection closed unexpectedly")`.
Interestingly, it happens with 
* self hosted ws DG endpoints
* ws proxy + wss deepgram cloud endpoints
but not wss deep cloud endpoints.
I found when that happens, the client session is already gone. This is to avoid such exceptions.
Tested with fallback as well, a connectivity issue will not cause client session closed, so fallback continue works.
Please feel free to let me know if you have better ideas. @longcw

Avoid session end deepgram errors

---

.github/next-release/changeset-9bd9e220.md
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/utils.py

OpenAI requires the tool call messages followed by the corresponding tool outputs, if there is a text message alongside the tool calls, we group the tool calls to the item of the message, there may be other conversation messages added between the tool calls and tool outputs causing the error
```python
ChatMessage(id='item_b3da83a73067', type='message', role='user', content=["What's the weather in Chicago today?"], interrupted=False, hash=None),
ChatMessage(id='item_6d8477a9f505', type='message', role='assistant', content=['I will now check the weather in Chicago for today. Please hold on for a moment.'], interrupted=False, hash=None),
ChatMessage(id='item_7a6b787c7a51', type='message', role='user', content=['Tell me a joke.'], interrupted=False, hash=None), …
```

fix tool format when there is messages between tool call and output

---

livekit-agents/livekit/agents/voice/agent_activity.py

I added the condition `GoogleRealtimeModel is not None` wrongly in previous pr.

fix generate_tool_reply for realtime model

---

livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/models.py

List new OpenAI 4.1-series models released today via the API in ChatModels

Add new OpenAI models to ChatModels

---

.github/next-release/changeset-785aff77.md
livekit-agents/livekit/agents/voice/audio_recognition.py

The _TurnDetector protocol definition was not consistent with existing plugin implementations. Updated the protocol to match the actual plugin usage.

fix: resolve type mismatch between _TurnDetector protocol and plugins

---

tests/conftest.py

```
app        | ==================================== ERRORS ====================================
app        | ____________ ERROR at teardown of test_synthesize_timeout[cartesia] ____________
app        | .venv/lib/python3.9/site-packages/pytest_asyncio/plugin.py:363: in finalizer
app        |     event_loop.run_until_complete(task)
app        | /usr/local/lib/python3.9/asyncio/base_events.py:647: in run_until_complete
app        |     return future.result()
app        | .venv/lib/python3.9/site-packages/pytest_asyncio/plugin.py:354: in async_finalizer
app        |     await gen_obj.__anext__()  # type: ignore[union-attr]
app        | tests/conftest.py:119: in fail_on_leaked_tasks
app        |     pytest.fail(final_msg)
app        | E   Failed: Test leaked resources:
app        | E   
app …
```

detect leaked tasks on tests 

---

.github/next-release/changeset-5e7650bc.md
livekit-agents/livekit/agents/voice/agent_session.py
livekit-agents/livekit/agents/voice/room_io/room_io.py

to avoid error when RoomIO already created explicitly
```python
room_io = RoomIO(session, room=ctx.room)
await room_io.start()
await session.start(
agent=..., room=ctx.room
)
```

avoid duplicate room io initialization

---

.github/next-release/changeset-d1555002.md
livekit-agents/livekit/agents/utils/connection_pool.py

This should address #2010 
In my testing, errors like `asyncio.CancelledError` are not captured (siblings of Exception) and have led to multiple dangling websocket connections (present in `_connections`, but not in `_available` or `_to_close`
change made to print out related issues
```
Connection context manager except block: CancelledError
Traceback (most recent call last):
File "/Users/chenghao/Developer/ai-worker/.venv/lib/python3.12/site-packages/livekit/agents/utils/connection_pool.py", line 78, in connection
yield conn
File "/Users/chenghao/Developer/ai-worker/.venv/lib/python3.12/site-packages/livekit/plugins/cartesia/tts.py", line 381, in _run
await asyncio.gather(*tasks)
File "/Users/chenghao/Developer/ai-worker/.venv/lib/python3.12/site-packages/livekit/plugins/cartesia/tts.py", …
```

Fix dangling websocket connections

---

livekit-agents/livekit/agents/voice/agent_activity.py

The agent-state was falsely returned to SPEAKING right after switching to LISTENING.
Tested with the openai realtime model after patching the code locally.
I have timers in my app relying on agent-state so this is a critical bug for me.

Bug Fix - wrong transition to SPEAKING when the agent is in fact listening

---

livekit-agents/livekit/agents/voice/agent_activity.py

When switching between agents using the workflow handoff feature, metrics events were being duplicated with each new agent. After one agent handoff, metrics would be doubled; after two handoffs, they would be tripled, and so on.
```
2025-04-23 22:32:57,295 - INFO livekit.agents - TTS metrics: ttfb=1.271504916017875, audio_duration=9.30 {"pid": 20532, "job_id": "AJ_cX6L8hCzAr6z"}
2025-04-23 22:32:57,295 - INFO livekit.agents - TTS metrics: ttfb=1.271504916017875, audio_duration=9.30 {"pid": 20532, "job_id": "AJ_cX6L8hCzAr6z"}
2025-04-23 22:32:57,299 - INFO livekit.agents - LLM metrics: ttft=0.43, input_tokens=165,  cached_input_tokens=0, output_tokens=15, tokens_per_second=22.37 {"pid": 20532, "job_id": "AJ_cX6L8hCzAr6z"}
2025-04-23 22:32:57,299 - INFO livekit.agents - LLM metrics: …
```

fix: prevent duplicate metrics when switching between agents

---

.github/next-release/changeset-cb19d9f7.md
livekit-agents/livekit/agents/llm/chat_context.py
livekit-agents/livekit/agents/llm/tool_context.py

Previously raw function tools definitions only worked when specified as class members. When specifying them directly when instantiating an Agent, it would fail because ChatContext#copy didn't know how to handle them.

fix using raw tools with ChatContext copies

---

livekit-agents/livekit/agents/llm/chat_context.py
livekit-agents/livekit/agents/voice/agent_activity.py

```python
async def on_user_turn_completed(self, turn_ctx: ChatContext, new_message: ChatMessage):
speech_handle = await self.session.say("This is an injected message")
```
Before: 
```
{"id":"item_eed0cfc736ee","role":"assistant","content":["This is an injected message"]},{"id":"item_5d337e233c63","role":"user","content":["Yo. What's up?"]},{"id":"item_84930d36a271","role":"assistant","content":["Hello! I'm here to help you with any questions or information you need. How can I assist you today?"]}
```
After:
```
{"id":"item_70e653ea1735","role":"user","content":["Yo. What's up?"]},{"id":"item_a776e29ab8eb","role":"assistant","content":["This is an injected message"]},{"id":"item_7a7e4ddc0d1a","role":"assistant","content":["Hello! I'm here to help you with any questions or information you …
```

ensure correct message ordering when injecting speeches in on_user_turn_completed

---

livekit-agents/livekit/agents/llm/chat_context.py

If `exclude_defaults` is `True`, the type won't be included in the dict and so you won't be able to convert the dict back to chat context

fix conversion of chat context to dict

---

.github/next-release/changeset-de15f366.md
livekit-plugins/livekit-plugins-google/livekit/plugins/google/tts.py

**Fix Google TTS Update Options Parameter Names**
This PR fixes the `update_options` method in the Google TTS plugin (`livekit.plugins.google.tts.TTS`), which was broken by incorrect internal parameter mapping introduced in [PR #2025](https://github.com/livekit/agents/pull/2025).
The parameter names used internally for `VoiceSelectionParams` have been corrected, restoring the ability to update language, gender, and voice name

fix(plugins-google): Fix Google TTS update options parameter names

---

livekit-plugins/livekit-plugins-hume/pyproject.toml

This resolves a dependency conflict on websockets when used with the google or openai plugins.

Set Hume SDK version to 0.8.3 or greater

---

livekit-agents/livekit/agents/ipc/mock_room.py

Running agents via the console (`python main.py console`) could lead to a `TypeError: bad argument type for built-in operation` when making API calls such as `api.DeleteRoomRequest(room=...)` or `api.RoomCompositeEgressRequest(room_name=...)`.
The root cause was that the simulated `JobContext` used in console mode relied on a mock `Room` object provided by `livekit.agents.ipc.mock_room`. This mock implementation assigned a `unittest.mock.MagicMock` object to its `.name` attribute. Protobuf message constructors expect a `str` for string fields and cannot handle `MagicMock` objects, resulting in the TypeError.
This commit fixes the issue by modifying the `MockRoom` implementation in `livekit/agents/ipc/mock_room.py`. The `.name` attribute is now explicitly cast to its string representation …

Bug fix: Ensure mock room name is string in console mode

---

.github/next-release/changeset-51b7bc26.md
livekit-agents/livekit/agents/utils/audio.py
livekit-agents/livekit/agents/utils/codecs/decoder.py
livekit-plugins/livekit-plugins-rime/livekit/plugins/rime/models.py
livekit-plugins/livekit-plugins-rime/livekit/plugins/rime/tts.py
tests/test_tts.py

Certain TTS (like Rime) would stream data back close to realtime. In those cases, it could increase the time it takes to receive the first frame due to libav decoder being conservative about buffering content. Switching to a streaming wav decoder to improve TTFB (Rime went from 1s to 300ms)

Improve decoding speed for wav

---

.github/next-release/changeset-63a32de3.md
livekit-plugins/livekit-plugins-google/livekit/plugins/google/tts.py

Fixes an issue introduced in: https://github.com/livekit/agents/pull/2139
https://github.com/livekit/agents/pull/2139#issuecomment-2845691859
This PR addresses an issue where Google TTS voices, specifically those in the Chirp3 family, could not be used due to incompatible audio encoding requests. The default PCM encoding used by the agent framework is not supported by these specific voices.
**Problem Details:**
When attempting to synthesize speech using a Chirp3 voice via `livekit.plugins.google.tts.TTS`, the underlying API rejects the request with a `400 Bad Request` status. The error message clearly states the supported output encodings: `ALAW`, `LINEAR16`, `MULAW`, `MP3`, and `OGG_OPUS`.
**Example Error Snippet**
`livekit.agents._exceptions.APIStatusError: This voice currently only …

fix(google-tts): Audio encoding for Chirp3 voices not compatible with PCM encoding

---

.github/next-release/changeset-4c7519f9.md
livekit-plugins/livekit-plugins-elevenlabs/livekit/plugins/elevenlabs/tts.py

ElevenLabs has support for SSML pauses in speech using  `<break time="0.3s" />`.
This PR adds support for them, in addition to the existing phonemes, waiting for the full tag to be present before passing it to TTS, not doing this can result in glitchy speech as it tries to speak partial XML.

Add ElevenLabs plugin support for SSML break tags

---

.github/next-release/changeset-bc4c7ae8.md
livekit-plugins/livekit-plugins-rime/livekit/plugins/rime/tts.py

This PR allows a user to override the default Rime URL in the case of using self-hosted deployments

Added ability to set custom Rime URL

---

.github/next-release/changeset-ed9ee113.md
livekit-plugins/livekit-plugins-google/livekit/plugins/google/llm.py
livekit-plugins/livekit-plugins-google/livekit/plugins/google/utils.py

Gemini requires generation requests to end with the user's turn
fixes #2180

Fix generate_reply for Gemini LLM

---

.github/next-release/changeset-2dbbc82b.md
livekit-plugins/livekit-plugins-google/livekit/plugins/google/beta/realtime/realtime_api.py

Hi Team, 
**Contribution** to fix: #2174 
**Context**: FunctionOutputResponse to a tool-call for realtime api was not getting sent to the gemini live api.  Because of deprecated function getting used.  
**Problem**: 
1. Whenever the tool response is injected back - the model speaks out as "tool_outputs" 
2. Model is not able to derive the context - from the tool-response(a.k.a) unable to understand. 
**Solution**: Using the latest apis - seems to be fixing this issue.
**Document link:** https://googleapis.github.io/python-genai/genai.html#module-genai.types
During several debugging found that the functionResponse should be always string - and it should not contain any special characters. 
```python
types.FunctionResponse(
id=msg.call_id,
name=msg.name,
response={"output": msg.output}, …
```

Fix: FunctionOutputResponse not getting recognised to gemini live-api

---

livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/tts.py

Deepgram has launched the **Aura-2** series of Text-to-Speech models. Currently, these models are **only supported via the REST API** — WebSocket support is expected to follow soon.
🔗 [Official Documentation](https://developers.deepgram.com/docs/streaming-text-to-speech)
- Implemented conditional handling to support both **Aura (legacy)** and **Aura-2** models.
- **Aura models** use **streaming mode (WebSocket)**.
- **Aura-2 models** use **non-streaming mode (REST API)**.
- Mode selection is determined by inspecting the model tag prefix (`aura` vs `aura-2`).
Once WebSocket support for Aura-2 is available, we can enable it through a future patch or hotfix.

Added Support for Rest-API based Deepgram Aura-2 - Version 0.x.

---

.github/next-release/changeset-70b208e6.md
livekit-plugins/livekit-plugins-elevenlabs/livekit/plugins/elevenlabs/tts.py

- using turbo as default model, as docstring indicates
- default chunk length as recommended by 11labs, instead of specifying an override

11labs: fix default model and chunk_length_schedule

---

livekit-plugins/livekit-plugins-bey/livekit/plugins/bey/avatar.py
livekit-plugins/livekit-plugins-tavus/livekit/plugins/tavus/avatar.py

This PR makes sure both plugins (bay & tavus) use the assigned LK api and secret, instead of reading from env.

Use assigned key and secret

---

livekit-agents/livekit/agents/cli/_run.py
livekit-agents/livekit/agents/cli/cli.py
livekit-agents/livekit/agents/cli/proto.py
livekit-agents/livekit/agents/jupyter.py
livekit-agents/livekit/agents/worker.py

60s default is too aggressive for most sessions to finish.
WorkerOptions is a more consistent place for users to set worker settings

move drain_timeout to WorkerOptions, increase default to 30 mins

---

livekit-agents/livekit/agents/tts/stream_adapter.py
livekit-agents/livekit/agents/worker.py

- also load every registered plugins
- processes are now launched instantly 0.02seconds instead of 3 seconds on the basic_agent.py example
Users can still use the old behaviour using `WorkerOptions(multiprocessing_context="spawn")`
This is safe as long as our plugins don't start threads at import time

use the forkserver on Linux by default 

---

.github/next-release/changeset-e65c5aa1.md
livekit-plugins/livekit-plugins-aws/pyproject.toml

Some users have complained that the dependency on `boto3==1.37.1` is too restrictive.  I tested LLM/STT/TTS with newest versions of each without any issues.
``` python
session = AgentSession(
vad=ctx.proc.userdata["vad"],
llm=aws.LLM(
model="anthropic.claude-3-5-sonnet-20240620-v1:0",
temperature=0.8,
),
stt = aws.STT(
language="en-US",
),
tts=aws.TTS(
voice="Ruth",
speech_engine="generative",
language="en-US",
),
turn_detection=multilingual.MultilingualModel(),
)
```

livekit-plugins-aws: update the dependencies to allow for versions greater than specified version

---

livekit-plugins/livekit-plugins-google/livekit/plugins/google/llm.py
livekit-plugins/livekit-plugins-google/livekit/plugins/google/models.py

Since Google has introduced implicit caching for the Gemini 2.5 Flash and Pro models, it’s beneficial to include information about cached input in the metrics. More details can be found in the official announcement: https://developers.googleblog.com/en/gemini-2-5-models-now-support-implicit-caching/
Additionally, this PR updates the list of available models for the Google LLM provider to include the newest Gemini versions.
Example log output:
```
2025-05-10 01:41:58,739 - INFO livekit.agents - LLM metrics: ttft=1.93, input_tokens=2834,  cached_input_tokens=1909, output_tokens=27, tokens_per_second=13.68 {"room": "playground-4xOP-jDVN", "pid": 88079, "job_id": "AJ_E8rmWvgTDawx"}
```

feat: support cached prompt metrics for Gemini LLM

---

.github/next-release/changeset-990dabed.md
livekit-agents/livekit/agents/tokenize/_basic_sent.py
livekit-agents/livekit/agents/tokenize/_basic_word.py
tests/test_tokenizer.py

A simple fix for character based languages (Chinese, Japanese, Korean, etc.) before https://github.com/livekit/agents/issues/1811
Fix https://github.com/livekit/agents/issues/1985

support simple word and sentence split for character-based language

---

livekit-agents/livekit/agents/utils/codecs/decoder.py

a previous PR disabled buffering in libav's internal decoder. this may be causing decoding issues when machine is under resource constraint.
while I'm unable to reproduce the crackling sound, these optimizations did not help with faster wav decodes so reverting them is the right thing here.
closes #2277

revert buffer changes to AudioStreamDecoder

---

.github/next-release/changeset-0374ff9a.md
examples/avatar_agents/bey/agent_worker.py
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/llm.py

This PR implements the `max_completion_tokens` parameter for the OpenAI LLM integration, as documented in the [OpenAI API reference](https://platform.openai.com/docs/api-reference/chat/create).
The parameter allows setting an upper bound for the number of tokens that can be generated for a completion, including both visible output tokens and reasoning tokens.
- Added `max_completion_tokens` to `_LLMOptions` dataclass
- Added parameter to LLM constructor
- Implemented parameter passing in chat method
```python
llm = LLM(
model="gpt-4",
max_completion_tokens=100  # Limits the response to 100 tokens
)
```
- Parameter is optional and follows the `NOT_GIVEN` pattern like other optional parameters
- Implementation follows existing codebase patterns
- No breaking changes introduced
- Added …

feat: Add max_completion_tokens parameter to OpenAI LLM

---

livekit-plugins/livekit-plugins-neuphonic/livekit/plugins/neuphonic/tts.py

This PR is a partial fix for https://github.com/livekit/agents/issues/2281.
This does NOT fix the underlying issue. But this small code change will result in Neuphonic having the same underlying behaviour to this bug as Cartesia currently does. I.e., this bug will result in the chatbot not crashing entirely, but simply logging an exception to the console and continuing as normal.

Partial fix for Neuphonic bug detailed in issue #2281. 

---

livekit-plugins/livekit-plugins-neuphonic/livekit/plugins/neuphonic/tts.py

Neuphonic tests are failing due to the code using `NEUPHONIC_API_TOKEN` but the github workflow setting `NEUPHONIC_API_KEY`.
This PR fixes this issue in a backwards compatible way.

Fix Neuphonic CI Tests.

---

livekit-plugins/livekit-plugins-google/livekit/plugins/google/beta/realtime/realtime_api.py
livekit-plugins/livekit-plugins-google/livekit/plugins/google/llm.py

This PR adds support for configuring Google LLM using environment variables for both Gemini and Vertex AI.
This can be useful, for example, when developing an agent worker locally using Gemini, while using Vertex AI in production. This behavior aligns with the `python-genai` library: https://googleapis.github.io/python-genai/#create-a-client
Additionally, it removes the warning about a missing `GOOGLE_APPLICATION_CREDENTIALS`, as Google supports other authentication methods such as Workload Identity, and the Google SDK handles credential checks and throws appropriate errors.
It also adds a missing default value for `location` in the Google LLM provider, in accordance with both the documentation and the Realtime API provider.

feat: allow to switch between Gemini and Vertex AI using env vars

---

livekit-agents/livekit/agents/voice/avatar/_runner.py

To avoid a green screen when video track published but not frame captured.

avatar runner publish audio/video tracks until first frame pushed

---

README.md

Hey all - I feel it'd be nice to have a weekly refresh of the codebase on deepwiki.com as it is evolving rapidly. Deepwiki needs the badge to be added for tracking the codebase to the weekly sync queue.
I am not associated with devin in any way but I find the tool pretty useful and others who are contributing might too.

added deepwiki badge for weekly repo refresh

---

.github/next-release/changeset-053d451c.md
livekit-agents/livekit/agents/llm/tool_context.py

It's possible to have function tools that do not need any arguments. The current code fails when passing an empty parameters array.

Support empty array of parameters when using raw_schema

---

.github/next-release/changeset-6a626bb2.md
livekit-agents/livekit/agents/voice/agent_activity.py

Currently, tool_choice is not usable when set to "required" or a specific function. This PR ensures tool_choice is reset to "auto" or "none" temporarily when passing back  tool response to the LLM, so it can be used practically.

fix tool choice

---

.github/next-release/changeset-7b1d7851.md
livekit-plugins/livekit-plugins-rime/livekit/plugins/rime/tts.py

The new `arcana` model can take much longer than `mistv2` due to it's architecture. As long as 80% of the duration of the actual audio. 
demonstrated by this curl request:  
```bash
curl -v -X POST "https://users.rime.ai/" \
-H "Authorization: Bearer $RIME_API_KEY" \
-H 'Accept: audio/wav' \
-H 'Content-Type: application/json' \
-d '{
"text": "oh, totally! like, um, okay so there was this one time, um, me and my friends went to this art festival in san francisco, right? and it was, like, super fun, but also kinda chaotic <laugh>. so, like, we were checking out all these booths with, like, amazing art and stuff, and I- I even brought along my sketchbook, um, to doodle, you know? so, like, at one point, I see this artist who was doing live paintings and, like, Ive never seen anything like …
```

[Rime] Increase timeout for `arcana` model to allow for synthesis of long audio 

---

.github/next-release/changeset-1b1bcfd3.md
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/llm.py

- previously temperature was not overridden in the extra_kwargs passed on chat.completion

Setting openai temperature on `LLM.chat`

---

livekit-plugins/livekit-plugins-google/livekit/plugins/google/beta/realtime/realtime_api.py

While there are still[ issues with proactivity and affective dialog on Googles end](https://discuss.ai.google.dev/t/new-live-api-features-dont-work-through-the-api-proactive-audio-and-affective-dialong/84326), this PR adds support for both and makes the realtime_input_config configurable.

Implemented #2379 - Add support for more paramaters for Google Live API

---

.github/next-release/changeset-afeb4064.md
livekit-agents/livekit/agents/voice/agent_activity.py

fix https://github.com/livekit/agents/issues/2436
When `llm` is None, `session.generate_reply` will create a speech handle but never processed that blocks the agent. User has to raise `StopResponse` in `on_user_turn_completed` if we don't skip the reply automatically.

skip response if no llm set in user turn completed

---

livekit-plugins/livekit-plugins-assemblyai/livekit/plugins/assemblyai/stt.py

- Remove the hardcoded default config
- Remove word boost (unsupported)
- Remove word_finalization_max_wait_time (no longer supported)

AssemblyAI Remove Hardcoded Default Configuration

---

.github/next-release/changeset-e1c5da38.md
livekit-agents/livekit/agents/voice/avatar/_datastream_io.py

make the audio frame duration configurable for avatar which needs a fixed window of audio

add duration_per_frame for datastream audio receiver

---

livekit-plugins/livekit-plugins-baseten/livekit/plugins/baseten/tts.py

This parameter isn't needed (and wasn't used) as the model_endpoint is the correct method to choose among your deployed models with baseten.
(not tested yet - @davidzhao I sent a request to join our org so I can verify and finish up the docs)

Remove unnecessary model param from baseten tts

---

.github/next-release/changeset-66686fac.md
livekit-plugins/livekit-plugins-turn-detector/livekit/plugins/turn_detector/base.py

when consecutive turns from the same are present in chat context, it confuses the turn detector since the model isn't trained to expect that case

fix(turn-detector): improve accuracy by combining adjacent turns

---

.github/next-release/changeset-4fe732da.md
livekit-plugins/livekit-plugins-hume/livekit/plugins/hume/__init__.py
livekit-plugins/livekit-plugins-hume/livekit/plugins/hume/tts.py

**Changes to Hume Plugin**
- Updates `PostedContext` type to support specifying context with a `generation_id`
- This is the more common way to specify [context](https://dev.hume.ai/reference/text-to-speech-tts/synthesize-json#request.body.context.ContextGenerationId.generation_id) in Hume's TTS API.
- Updates plugin to no longer default `context` to `None`, despite presence of user provided `context`.
- Updates default sample rate from `24kHz` to `48kHz` and removes the `sample_rate` option.
- Sample rate should not be configurable for this plugin, because the Hume TTS API only outputs audio with a sample rate of 48kHz. The sample rate of speech audio is not currently configurable through the API.)
- Add `audio_format` option to make audio format configurable.
- The plugin currently …

Hume plugin fixes

---

.github/next-release/changeset-cf5a2ec7.md
livekit-agents/livekit/agents/cli/log.py
livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model.py

Update cached_tokens_details (`livekit-plugins/livekit-plugins-openai/livekit/plugins/openai/realtime/realtime_model.py`)
This update will help you obtain more accurate metrics on tokens spent, which means you will be able to calculate costs more accurately:
```python
prices_llm = {
"ctp": 2.5,
"itp": 5,
"iap": 40,
"otp": 20,
"oap": 80
} # gpt-4o-realtime-preview ($ per M tokens)
def _on_metrics_collected(self, ev: RealtimeModelMetrics):  
metric_data = {
"cached_text_tokens": ev.metrics.input_token_details.cached_tokens_details.text_tokens,
"cached_audio_tokens": ev.metrics.input_token_details.cached_tokens_details.audio_tokens,
"input_text_tokens": ev.metrics.input_token_details.text_tokens,
"input_audio_tokens": ev.metrics.input_token_details.audio_tokens,
"output_text_tokens": …
```

Updating metrics for cached tokens for Realtime model (OpenAI)

---

.github/next-release/changeset-955cda8e.md
livekit-plugins/livekit-plugins-hume/livekit/plugins/hume/tts.py

- **Remove the `split_utterances` option.**
- The `split_utterances` flag only alters how the API’s `snippets` array is structured in the response body. 
- Since the plugin extracts and returns only the raw audio payload, this setting has no effect on end-user output and can be removed to simplify the plugin's interface.

Removes the split_utterances option from Hume TTS plugin

---

.github/next-release/changeset-e46145c3.md
livekit-agents/livekit/agents/voice/background_audio.py

We observe frequent timeouts for the background audio.
I increased the default timeout to fix it.
Other options are 
- Increasing default timeout of `AudioMixer`
- Adding param `audio_mixer_kwargs` to `BackgroundAudioPlayer`
- Adding param `stream_timeout_ms` to `BackgroundAudioPlayer`
What would be the preferred approach?

Fix : Increase audio mixer timeout

---

.github/next-release/changeset-8f8eb6a2.md
.github/next-release/changeset-e46145c3.md
livekit-agents/livekit/agents/voice/background_audio.py
livekit-plugins/livekit-plugins-gladia/README.md
livekit-plugins/livekit-plugins-gladia/livekit/plugins/gladia/stt.py

This update enhances the documentation for the Gladia plugin usage by:
Expanding the advanced GladiaSTT configuration example with additional parameters:
- translation_context_adaptation, translation_context, and translation_informal for more control over translation behavior.
- pre_processing_audio_enhancer and pre_processing_speech_threshold to fine-tune audio preprocessing.
Introducing real-world examples for:
- custom_vocabulary: includes weighted entries and optional pronunciation hints.
- custom_spelling: demonstrates normalization of alternative spellings or phonetic variants.

Gladia STT - add new parameters to gladia stt

---

livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/stt.py

align with deepgram default: https://developers.deepgram.com/docs/smart-format

deepgram: disable smart_format by default

---

livekit-plugins/livekit-plugins-google/pyproject.toml

This change pins the google-genai package to version 1.20.0 to avoid a `JSONDecodeError` and an `ERROR asyncio - Unclosed client session` that occur during streaming with version 1.21.1 and above.
https://github.com/googleapis/python-genai/issues/1024
https://github.com/googleapis/python-genai/issues/1014

Lock google-genai package to stable v1.20.0

---

livekit-agents/livekit/agents/voice/agent_activity.py

Before python 3.13, on Windows, time.monotonic() uses gGetTickCount64() clock which has a resolution of 15.6 ms.
https://github.com/python/cpython/pull/116781
Replaced it with `time.perf_counter_ns` for python < 3.13 on Windows, fix https://github.com/livekit/agents/issues/2764

fix schedule speech on windows when monotonic_ns resolution is rough

---

livekit-agents/livekit/agents/voice/generation.py

This is purely for devex purposes inside the evals API e.g:
```
with mock_tools(
DriveThruAgent, {"order_regular_item": lambda: RuntimeError("test failure")}
):
```

allow returning Exception inside function tools

---

livekit-agents/livekit/agents/voice/agent_activity.py

We started our proof of concept using `session.generate_reply()`.
When the user interrupted the agent, it was useful to have only the part which was actually spoken for `interrupted` messages.
When we moved to generating responses separately in our platform and then using `session.say()`, `interrupted` messages would contain the full content - not just the portion which was read aloud.
This PR aims to align the behaviour of `session.say()` to `session.generate_reply()` by only adding the spoken content to the chat context for interrupted messages.

Fix: Use synchronized transcript for interrupted session.say() responses

---

livekit-plugins/livekit-plugins-elevenlabs/livekit/plugins/elevenlabs/tts.py

fix https://livekit-users.slack.com/archives/C07FY8WHGPM/p1753207414610429
it shouldn't raise error when `audio` is an empty string
> livekit.agents._exceptions.APIError: unexpected 11labs message {'audio': '', 'isFinal': None, 'normalizedAlignment': None, 'alignment': None} (body=None, retryable=True)

fix 11labs tts when audio is an empty string

---

livekit-agents/livekit/agents/voice/chat_cli.py

Restore the cursor position after printing so that other logging appears above the status line
Before:
```shell
[Audio] cBook Air Microphone [-65.09 dBFS] [##----------------------------]log message
```
After:
```
log message
[Audio] cBook Air Microphone [-65.09 dBFS] [##----------------------------]
```

Improve chat_cli status printing

---

livekit-plugins/livekit-plugins-aws/livekit/plugins/aws/stt.py

fix https://github.com/livekit/agents/issues/2961
when restarting the aws stt, it stuck at `await client.start_stream_transcription`, seems that the client cannot be reused.

fix aws stt restarting

---

livekit-plugins/livekit-plugins-google/livekit/plugins/google/beta/realtime/api_proto.py

https://ai.google.dev/gemini-api/docs/live#audio-generation
A much more stable version of Gemini: gemini-live-2.5-flash-preview.

enable - gemini-live-2.5-flash-preview

---

livekit-agents/livekit/agents/voice/io.py

When `session.input.set_audio_enabled(False)` called before agent io set (e.g. `session.start()`), inputs and outputs set later is not detached properly.

fix: call on_attached or on_detached when set agent input and output

---

livekit-plugins/livekit-plugins-cartesia/livekit/plugins/cartesia/tts.py

cartesia tts returns an error `{'type': 'error', 'context_id': '49c376fe1e6a', 'status_code': 400, 'done': True, 'error': 'transcript empty or contains only punctuation: first transcript for WS is empty or contains only punctuation'}` when input text is empty.
ignore the error message if `done` is True.
fix https://github.com/livekit/agents/issues/3084

fix cartesia error when input text is empty

---

livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/stt.py

Deepgram's new EU endpoint offers lower latency for EU usage: `https://api.eu.deepgram.com/v1/listen` (benchmarked it, it makes a good difference).
issue: https://github.com/livekit/agents/issues/3085

add endpoint_url in deepgram STT options

---

livekit-agents/livekit/agents/voice/agent.py

I can't think of a reason why we would want to `wait_on_enter` when resuming the same `Agent` after executing an `AgentTask`. By making this fix, it also makes the example workflow in the documentation not halt after the first question.
The example workflow:
```python agent.py console```
**agent.py**
```
from dotenv import load_dotenv
from livekit import agents
from livekit.agents import AgentSession, Agent, AgentTask, function_tool
from livekit.plugins import openai, silero
load_dotenv()
class CollectConsent(AgentTask[bool]):
def __init__(self, chat_ctx):
super().__init__(
instructions="Ask for recording consent and get a clear yes or no answer.",
chat_ctx=chat_ctx
)
async def on_enter(self) -> None:
await self.session.generate_reply(instructions="Ask for permission to record the call …
```

Do not `wait_on_enter` when resuming `Agent` after `AgentTask` execution

---

examples/voice_agents/langfuse_trace.py
livekit-agents/livekit/agents/voice/agent_session.py

fix the issue when call the `session._aclose_impl` outside the agent session (e.g. in `shutdown_callback`), the activity drain and on_exit spans are in a separate trace.

trace: attach agent session root span before closing

---

livekit-agents/livekit/agents/ipc/proc_pool.py
livekit-agents/livekit/agents/utils/hw/cpu.py
livekit-agents/livekit/agents/worker.py
livekit-plugins/livekit-plugins-turn-detector/livekit/plugins/turn_detector/base.py

the way we get CPU count isn't accurate. on cgroupsv1 instances, the quota is often unset, leading it to still use the host CPU count.
here we'll put a upper cap on concurrent processes spun up as well as idle processes, to reduce the likelihood that it'll try to use the entire machine

feat: cgroups v1 support, lower idle processes

---

livekit-agents/livekit/agents/utils/hw/cpu.py
livekit-agents/livekit/agents/worker.py

often cgroupsv1 does not set the quota properly. this could cause issues on environments like AWS ECS where we are led to believe there are 64 cores available to the agent, when only 3 are assigned.
for those environments, it's now possible to set an environment variable `NUM_CPUS`, indicating the number of cores that the agent is allowed to use

fix: allow CPU override from environment

---

livekit-plugins/livekit-plugins-aws/livekit/plugins/aws/models.py
livekit-plugins/livekit-plugins-aws/livekit/plugins/aws/tts.py

[AWS Polly](https://docs.aws.amazon.com/polly/latest/dg/API_SynthesizeSpeech.html#polly-SynthesizeSpeech-request-TextType) supports `ssml` text type, adds `text_type` to TTSOptions with `text` as default.

feat(aws-polly): add support for ssml text type

---

livekit-plugins/livekit-plugins-google/livekit/plugins/google/tts.py

According to the official cloud_tts the passing parameter should be `voice_cloning_key` not `voice_clone_key`. I had tested my custom livekit plugin it and works properly.
```
class VoiceCloneParams(proto.Message):
r"""The configuration of Voice Clone feature.
Attributes:
voice_cloning_key (str):
Required. Created by GenerateVoiceCloningKey.
"""
voice_cloning_key: str = proto.Field(
proto.STRING,
number=1,
)
```
I believe the related issue is here: https://github.com/livekit/agents/issues/3013
@davidzhao

fix(google): Instant Voice Cloning Key Parameter is incorrect

---

livekit-plugins/livekit-plugins-google/livekit/plugins/google/stt.py

When using `google.TTS(model="chirp_2", enable_word_time_offsets=False)`, since there is no word offsets, the `resp.results[0].alternatives[0].words[0].start_offset` call in `_recognize_response_to_speech_event` raise an error.
```
Traceback (most recent call last):
File "agents/livekit-plugins/livekit-plugins-google/livekit/plugins/google/stt.py", line 267, in _recognize_impl
return _recognize_response_to_speech_event(raw)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "agents/livekit-plugins/livekit-plugins-google/livekit/plugins/google/stt.py", line 565, in _recognize_response_to_speech_event
start_offset = resp.results[0].alternatives[0].words[0].start_offset
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
File ".venv/lib/python3.12/site-packages/proto/marshal/collections/repeated.py", line …
```

Fix Google STT Word‑timings error.

---

livekit-plugins/livekit-plugins-elevenlabs/livekit/plugins/elevenlabs/stt.py

This is the official explanation: https://elevenlabs.io/docs/api-reference/speech-to-text/convert#request.body.tag_audio_events.tag_audio_events

feat: add option to tag audio events in ElevenLabs STT

---

examples/voice_agents/silent_function_call.py
livekit-agents/livekit/agents/voice/agent_activity.py
livekit-agents/livekit/agents/voice/events.py

if there are parallel tool calls, the tool executions won't know each other. this is useful when ppl want to skip the tool response when another tool returns a new Agent.

add `cancel_tool_reply` to function_tools_executed event

---

livekit-plugins/livekit-plugins-langchain/livekit/plugins/langchain/langgraph.py

**What & why**
Adds optional `subgraphs: bool=False` to `LLMAdapter` and normalizes the various tuple shapes emitted by `graph.astream(..., stream_mode="messages")`. This enables LiveKit to stream tokens from LangGraph **subgraphs** (child graphs) when `subgraphs=True`.
**Changes**
* `LLMAdapter.__init__(..., subgraphs: bool=False)`; threaded into `LangGraphStream`.
* `LangGraphStream._run()`:
* Calls `graph.astream(..., subgraphs=self._subgraphs)` with a `TypeError` fallback.
* Normalizes items via `_extract_message_chunk(...)` to pull out `token` regardless of tuple shape.
* Keeps `ChatChunk` emission logic unchanged.
**BC & compatibility**
* Backward compatible; default is `subgraphs=False`.
* Older LangGraph versions: graceful fallback (retry without `subgraphs` kwarg).
**Linked …

feat(langgraph): support subgraphs in LLMAdapter and normalize astream outputs

---

livekit-plugins/livekit-plugins-azure/livekit/plugins/azure/stt.py

This pull request adds support for configuring punctuation behavior in the Azure Speech-to-Text (STT) plugin. The main change is the introduction of a new `punctuation` option, allowing users to explicitly control how punctuation is handled during speech recognition.
**Azure STT punctuation option support:**
* Added a `punctuation` field to the `STTOptions` class, allowing users to specify punctuation handling.
* Updated the `STT` class constructor to accept the new `punctuation` parameter and documented its behavior in the docstring. [[1]](diffhunk://#diff-e385d376ee185b8e05288d55722a2672de5aae917b2d20f50a0bc86be4af9259R81) [[2]](diffhunk://#diff-e385d376ee185b8e05288d55722a2672de5aae917b2d20f50a0bc86be4af9259R97-R98)
* Passed the `punctuation` option through to the internal …

feat(azure-stt): add configurable punctuation option to Azure STT

---

livekit-agents/livekit/agents/tts/fallback_adapter.py

FallbackAdapter currently requires ALL TTS instances to support streaming before reporting streaming capability. This forces the Agent framework to wrap streaming-capable adapters with StreamAdapter, breaking native WebSocket streaming even when the primary TTS supports it.
- Change streaming capability detection to prioritize primary TTS
- Add runtime fallback for non-streaming TTS instances using StreamAdapter  
- Enables native WebSocket streaming for primary TTS while maintaining fallback compatibility
- Modified [FallbackAdapter.__init__()](cci:1://file:///home/borislav/VSCode/tt-demo2/toy_assistant/agent.py:74:4-108:9) to use `tts[0].capabilities.streaming or any(t.capabilities.streaming for t in tts)`
- Added runtime StreamAdapter wrapping in …

fix: improve FallbackAdapter streaming capability detection

---

livekit-agents/livekit/agents/voice/agent_session.py

addresses #3396 
removed converting the end time to nanoseconds for an accurate speaking duration span

fix user speaking span duration

---

livekit-plugins/livekit-plugins-sarvam/livekit/plugins/sarvam/tts.py

This PR updates the **Sarvam.ai TTS integration** in LiveKit agents to support the recently released `bulbul:v3-beta` model.  
- Sarvam deprecated the **mandatory `pitch` and `loudness` parameters** in `bulbul:v3-beta`.  
- LiveKit’s existing integration enforces these fields, which causes runtime errors when developers try the new model.  
- Made `pitch` and `loudness` optional → only included in API payload for `bulbul:v2`.  
- Introduced **model-speaker compatibility validation** to avoid misconfiguration.  
- Developers can now use both **`bulbul:v2`** and **`bulbul:v3-beta`** seamlessly.  
- Backward compatibility is preserved for v2 users.  
- Unlocks testing and adoption of Sarvam’s new TTS model within LiveKit.  
https://www.notion.so/sarvamai/Bulbul-V3-Beta-testing-26539c96b62d802 …

fix(sarvam-tts): add bulbul:v3-beta support and make pitch/loudness optional

---

livekit-plugins/livekit-plugins-google/livekit/plugins/google/tts.py

Adds support for [Google TTS pause control markup](https://cloud.google.com/text-to-speech/docs/chirp3-hd#pause_control) by extending the `tts_node`.
I noticed that **when `use_tts_aligned_transcript=True` (default), the transcript also outputs the `[pause]` markup**, which might not be ideal for frontend display.  
Would you recommend flagging this in the code itself, or is it better documented in the integration guide?

feat(Google): Add markup for TTS HD voices

---

livekit-agents/livekit/agents/llm/chat_context.py

This PR resolves a bug in the ChatContext.truncate() method where the system message could be duplicated when truncation was applied on a context with fewer items than max_items. The fix is simple and quite self explanatory.

Bug fix: Safe handling in ChatContext.truncate() when fewer items than max_items

---

livekit-plugins/livekit-plugins-cartesia/livekit/plugins/cartesia/models.py

We updated the default voice across our Cartesia platform to [Katie](https://play.cartesia.ai/voices/f786b574-daa5-4673-aa0c-cbe3e8534c02), so reflecting that in the LiveKit integration.
I ran a livekit agent locally with the new default voice.

[Cartesia] Upgrade Default Voice

---

CONTRIBUTING.md

It wasn't immediately clear to me as a contibutor what commands to run for linting/typechecking/formatting without inspecting what the CI scripts were doing, so thought it would be nice to make it more explicit. In particular, even after reading the CI scripts, I didn't notice you need to run a `uv pip install pip` before the `uv run mypy` will work, so I hope this will help other contributors get up and running faster.

docs(CONTRIBUTING.md): add linting/formatting command guideline

---

livekit-agents/livekit/agents/llm/llm.py
livekit-agents/livekit/agents/metrics/base.py
livekit-agents/livekit/agents/metrics/utils.py

I need to analyze LLM metrics logs to calculate costs. Since each agent uses a different LLM model, it is necessary to add a model field in the logs.

feat: add model attribute to metrics tracking in LLM

---

livekit-agents/livekit/agents/voice/agent_activity.py

Without these, we see a new OpenTelemetry span being created for each realtime_assistant_turn
Before this PR:
- Many spans per session
After:
- A single span  per session

fix(agent_activity): correctly nest OpenTelemetry spans within existing spans

---

livekit-agents/livekit/agents/voice/room_io/room_io.py

when the `AgentSession` closes, the room is deleted by default

add delete_room_on_close to RoomInputOptions

---

livekit-agents/livekit/agents/voice/agent_activity.py

Add race condition check in _scheduling_task to avoid processing already-done speeches after min_consecutive_speech_delay sleep. This prevents potential deadlocks when speech.done() changes between the initial check and generation authorization.
- Add speech.done() check after asyncio.sleep() in delay branch
- Only check when min_consecutive_speech_delay > 0.0 to optimize performance
- Prevents calling _authorize_generation() on completed speeches
fix: https://github.com/livekit/agents/issues/3496

fix: prevent deadlock in speech scheduling after consecutive delay

---

livekit-agents/livekit/agents/llm/_provider_format/google.py

When a tool output didn't create a response, the follow up user message may be added to the same turn of the tool output, the expect messages are like following:
```python
{'parts': [{'text': "Yeah. What's the word in New York?"}], 'role': 'user'},
{'parts': [{'text': 'I can look up the weather for you in New York. I will '
'need the latitude and longitude for that, but I can '
'estimate'}],
'role': 'model'},
{'parts': [{'text': 'Yes.'}], 'role': 'user'},
{'parts': [{'function_call': {'args': {'latitude': '40.7128',
'location': 'New York',
'longitude': '-74.0060'},
'id': 'function_call_7bd887d7da6c',
'name': 'lookup_weather'}}],
'role': 'model'},
{'parts': [{'function_response': {'id': 'function_call_7bd887d7da6c',
'name': 'lookup_weather',
'response': {'output': ''}}}],
'role': 'user'}, …
```

fix gemini llm: avoid mixing tool output and user message in a single turn

---

livekit-agents/livekit/agents/job.py
livekit-agents/livekit/agents/worker.py

Revert "add terminate to JobRequest"

---

livekit-plugins/livekit-plugins-hume/livekit/plugins/hume/__init__.py
livekit-plugins/livekit-plugins-hume/livekit/plugins/hume/tts.py

- Adds new `ModelVersion` type alias for supported Hume TTS model versions.
- Included in type exports for plugin.
- Adds `model_version` parameter to `_TTSOptions`. 
- This change enables users to specify Octave 2 in their requests. 
- [Octave 2](https://www.hume.ai/blog/octave-2-launch) is the latest version of Hume's TTS model.
- Fixes typo in doc string for `voice_id` field.

feat(livekit-plugins-hume): add model_version parameter

---

livekit-agents/livekit/agents/job.py
livekit-agents/livekit/agents/worker.py

Passing `api_key`, `api_secret`, and `ws_url` via `WorkerOptions` didn’t affect `ctx.api` because `JobContext.api` reads credentials from environment variables. This caused failures when env vars weren’t set.
After validating options in Worker.__init__, export:
```
LIVEKIT_URL = opts.ws_url
LIVEKIT_API_KEY = opts.api_key
LIVEKIT_API_SECRET = opts.api_secret
```
So child job processes/threads inherit the correct credentials. Updated `JobContext.api` docstring accordingly.
`ctx.api` now works when creds are provided only via `WorkerOptions`.
Backwards compatible with env-based config and CLI flags.

Ensure ctx.api uses WorkerOptions credentials by exporting LIVEKIT_* in worker

---

livekit-plugins/livekit-plugins-google/livekit/plugins/google/beta/realtime/api_proto.py
livekit-plugins/livekit-plugins-google/livekit/plugins/google/beta/realtime/realtime_api.py

- Add support for `thinking_config` parameter in RealtimeModel and RealtimeSession
- Enables native audio thinking configuration for Gemini models
- Parameter is properly threaded through the configuration setup
- Add `gemini-2.5-flash-native-audio-preview-09-2025` to supported models
- Expand available voice options from 8 to 31 voices
- Added voices: Achernar, Achird, Algenib, Algieba, Alnilam, Autonoe, Callirrhoe, Despina, Enceladus, Erinome, Gacrux, Iapetus, Laomedeia, Pulcherrima, Rasalgethi, Sadachbia, Sadaltager, Schedar, Sulafat, Umbriel, Vindemiatrix, and Zubenelgenubi
- Existing voices retained: Puck, Charon, Kore, Fenrir, Aoede, Leda, Orus, Zephyr
- Update audio mime type to include sample rate (`audio/pcm;rate={INPUT_AUDIO_SAMPLE_RATE}`)

feat(google): Add thinking_config support, new model, and expanded voice profiles for google gemini TTS

---

livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/stt_v2.py

Deepgram v2 returns a string error code when they are surfacing errors. The most prominent example of this is timeout. if we are not sending data for awhile, DG will timeout with `INACTIVE_CLIENT`, which we were parsing incorrectly as an int.

fix(deepgram): correctly handle timeout related errors
